In [144]:
print("hi")

hi

In [145]:
import pandas as pd

In [146]:
df=pd.read_csv("final7486_test_s3.csv")

In [147]:
df.head()

,sample_id,catalog_content,image_link,item_name,value,unit,pack,unit_clean,text_embeddings,image_embeddings,extra_attributes
0,100179,item name: rani 14-spice eshamaya's mango chut...,https://m.media-amazon.com/images/I/71hoAn78AW...,rani 14-spice eshamaya's mango chutney (indian...,10.5,ounce,1,ounce,"[0.036331795156002045, -0.052913691848516464, ...","[0.009049994871020317, 0.00274485326372087, -0...","vegan, non-gmo, premium, gourmet"
1,245611,item name: natural milk tea flavoring extract ...,https://m.media-amazon.com/images/I/61ex8NHCIj...,natural milk tea flavoring extract by halo pan...,2.0,fl oz,1,fl oz,"[-0.01868608593940735, -0.013683686032891273, ...","[0.014290607534348965, -0.04910419136285782, 0...","dye-free, gourmet, gluten-free, dairy-free, so..."
2,146263,item name: honey filled hard candy - bulk pack...,https://m.media-amazon.com/images/I/61KCM61J8e...,honey filled hard candy - bulk pack 2 pounds -...,32.0,ounce,1,ounce,"[0.07000485807657242, -0.06418927758932114, -0...","[-0.010892418213188648, -0.038370147347450256,...",NaN
3,95658,item name: vlasic snack'mm's kosher dill 16 oz...,https://m.media-amazon.com/images/I/51Ex6uOH7y...,vlasic snack'mm's kosher dill 16 oz (pack of 2),2.0,count,2,count,"[-0.04193189740180969, -0.02518327534198761, 0...","[0.058143433183431625, -0.004104044754058123, ...",NaN
4,36806,"item name: mccormick culinary vanilla extract,...",https://m.media-amazon.com/images/I/71QYlrOMoS...,"mccormick culinary vanilla extract, 32 fl oz -...",32.0,fl oz,1,fl oz,"[0.021312430500984192, 0.0017853323370218277, ...","[-0.035538848489522934, 0.009405052289366722, ...","non-gmo, pure, premium, satisfying, fragrant, ..."

In [148]:
df["image_embeddings"][0]

'[0.009049994871020317, 0.00274485326372087, -0.030127644538879395, -0.02061096578836441, 0.0438159704208374, -0.02496897056698799, -0.013341407291591167, 0.01859249174594879, -0.00926909688860178, 0.01017041690647602, -0.04977896064519882, 0.003680315800011158, 0.007888146676123142, -0.0071112774312496185, 0.01168571226298809, -0.01703706942498684, 0.13816556334495544, 0.05456237867474556, -0.030592763796448708, 0.0006587631069123745, -0.13664460182189941, -0.03216315433382988, -0.0006562460330314934, -0.018323760479688644, -0.044929150491952896, 0.07610122859477997, 0.018811412155628204, 0.016470521688461304, -0.02357197180390358, -0.006560056004673243, 0.02112066000699997, 0.04596182703971863, -0.04166111350059509, 0.06595196574926376, 0.033217817544937134, -0.06342346966266632, -0.014267143793404102, 0.010462078265845776, -0.047609176486730576, 0.0894441306591034, 0.009533942677080631, -0.016992267221212387, 0.03446492180228233, -0.014851999469101429, 0.03837830200791359, 0.08044318854808807, -0.0013417055597528815, 0.0002129231725120917, 0.021155033260583878, -0.011057971976697445, 0.01963398978114128, -0.014173916541039944, 0.0406266525387764, 0.012332096695899963, 0.006164335645735264, 0.04386601224541664, -0.012793491594493389, 0.0023214868269860744, 0.07112672924995422, -0.003595843445509672, -0.007416451349854469, -0.0072309463284909725, -0.04704386368393898, 0.027784325182437897, 0.006830951664596796, 0.028855828568339348, 0.0003048846556339413, 0.09291604906320572, 0.0027148586232215166, -0.007206350099295378, -0.0473003014922142, -0.004022889770567417, -0.0004512309096753597, -0.012881837785243988, -0.02967105060815811, 0.0036036192905157804, 0.02147834189236164, -0.0020291947294026613, -0.007462749257683754, 0.002378127072006464, 0.035394586622714996, 0.009227643720805645, -0.002578006125986576, -0.06853917986154556, 0.02278219908475876, 0.04295443370938301, -0.02403859794139862, -0.029629984870553017, 0.058468230068683624, 0.05016835406422615, 0.05730418115854263, 0.030966592952609062, -0.5469426512718201, -0.0060609919019043446, 0.028984593227505684, 0.0222794059664011, -0.027054913341999054, 0.03976397588849068, -0.056131552904844284, 0.010572567582130432, 0.06153324246406555, -0.01073937676846981, -0.024838486686348915, -0.03978447616100311, -0.06648034602403641, -0.014277119189500809, -0.044879741966724396, 0.03613010048866272, 0.01842050999403, 0.0042005195282399654, 0.005773109383881092, 0.06601693481206894, -0.058665379881858826, 0.018934130668640137, 0.016893060877919197, -0.038078077137470245, 0.009964014403522015, 0.010051561519503593, -0.006467730738222599, -0.07532129436731339, 0.07211798429489136, 0.0057959724217653275, 0.01153398584574461, 0.012306549586355686, 0.0017606131732463837, -0.0025651524774730206, -0.007914715446531773, 0.013811939395964146, 0.03517674282193184, -0.08025530725717545, -0.041332144290208817, 0.024120746180415154, 0.007461934816092253, 0.08962400257587433, 0.0014573805965483189, 0.025256993249058723, 0.04263710230588913, -0.006029365584254265, -0.004849948920309544, -0.03707686811685562, 0.012438558042049408, 0.01727296970784664, -0.01907660998404026, 0.048418283462524414, -0.008199486881494522, 0.0094028040766716, -0.022273704409599304, 0.043641507625579834, 0.024548200890421867, 0.021567124873399734, -0.019674988463521004, -0.0034774162340909243, 0.04964248463511467, 0.004471260588616133, -0.03275483474135399, -0.061284467577934265, 0.04424067214131355, 0.04066331684589386, -0.04500264674425125, -0.031770821660757065, -0.04365229234099388, 0.02945910580456257, 0.06301846355199814, -0.018998876214027405, 0.007050978485494852, 0.036649975925683975, 0.021127190440893173, -0.0400032177567482, -0.019337035715579987, 0.0016961494693532586, -0.05182497575879097, -0.02340419590473175, 0.009573384188115597, 0.003690136130899191, -0.016934778541326523, 0.009789576753973961, -0.012273348867893219, 0.0062964861281216145, 0.1582868993282318, -0.003194083459675312, 0.045167066156864166, 0.040546733886003494, -0.01316189393401146, 0.017786283046007156, -0.0016735867829993367, 0.0028470992110669613, -0.00997550692409277, 0.03541383147239685, -0.020926473662257195, -0.009583844803273678, 0.01436078455299139, 0.0007426241063512862, -0.040987785905599594, -0.018658343702554703, 0.05320826917886734, 0.001145306508988142, -0.011396477930247784, -0.029204294085502625, 0.015343395061790943, -0.020371632650494576, 0.01609712652862072, -0.040076203644275665, 0.03692255914211273, 0.019084379076957703, 0.009523901157081127, 0.023886162787675858, -0.08209483325481415, 0.01551771815866232, -0.00967962946742773, 0.01886509358882904, -0.006164677441120148, 0.12572458386421204, 0.0032835702877491713, 0.08418550342321396, 0.0014450144954025745, 6.300585027929628e-06, -0.009949888102710247, -0.013782205060124397, 0.020832328125834465, 0.05216062441468239, -0.0014055714709684253, 0.07647399604320526, -0.026461955159902573, -0.014764823950827122, 0.03613137826323509, -0.024653730913996696, -0.011703248135745525, -0.035421594977378845, 0.048771604895591736, -0.0012463401071727276, -0.008940660394728184, -0.035109154880046844, 0.010862250812351704, -0.030336037278175354, 0.008659071289002895, 0.03452456369996071, -0.0023563371505588293, -0.028556158766150475, -0.029377466067671776, 0.0241090040653944, 0.013002307154238224, -0.009430120699107647, 0.0020637926645576954, -0.02257395349442959, -0.015400259755551815, -0.028227536007761955, 0.0664791688323021, 0.10037978738546371, -0.009998386725783348, 0.015351926907896996, 0.008171730674803257, -0.022017493844032288, -0.003164843888953328, -0.0031131694559007883, 0.02091214805841446, 0.09593634307384491, -0.021146206185221672, -0.012006795965135098, -0.05132623761892319, 0.02172933891415596, 0.0058848368935287, 0.020520100370049477, 0.009249246679246426, 0.04696958512067795, -0.06759562343358994, 0.05426213517785072, 0.026737574487924576, 0.00807182490825653, 0.0726017877459526, 0.0038997558876872063, -0.020937643945217133, 0.010169369168579578, -0.02077990584075451, 0.018077759072184563, 0.004450296983122826, -0.021592574194073677, -0.04074824973940849, -0.012521252036094666, -0.013972046785056591, 0.014736199751496315, -0.04574985429644585, 0.01915593072772026, -0.01995493844151497, 0.015259337611496449, 0.009586472064256668, 0.028561502695083618, 0.05185262858867645, 0.021580982953310013, -0.03252410143613815, -0.0010877412278205156, 0.05776587873697281, 0.017730074003338814, -0.05635448172688484, -0.009009859524667263, -0.05315503478050232, 0.003430176293477416, 0.08774688094854355, -0.008808312006294727, 0.007353223394602537, 0.006255166605114937, -0.04683087766170502, 0.0008017446962185204, -0.012631352990865707, -0.007673855405300856, -0.016912993043661118, -0.01815130189061165, -0.015859929844737053, -0.001944831688888371, -0.0031205504201352596, -0.05476952716708183, 0.016178825870156288, 0.01999134011566639, 0.08959633111953735, -0.01722007803618908, -0.023224178701639175, 0.05510953068733215, 0.021616367623209953, 0.06651069223880768, 0.02436772733926773, 0.006131923291832209, -0.007461105473339558, 0.11571147292852402, -0.018109029158949852, -0.035682059824466705, -0.0570937842130661, -0.019949713721871376, 0.04425835236907005, 0.00774277001619339, 0.07766303420066833, 0.002582005923613906, 0.011965443380177021, 0.012664876878261566, -0.0018032601801678538, -0.011617295444011688, 0.0026738925371319056, 0.03132273629307747, 0.03855092450976372, 0.012515370734035969, -0.0017017415957525373, 0.04428860545158386, -0.029442941769957542, -0.047170449048280716, 0.053538061678409576, -0.02953544817864895, 0.024267207831144333, -0.034508004784584045, -0.0223613940179348, 0.023029472678899765, -0.001559432246722281, 0.013794727623462677, -0.017591459676623344, -0.09672696143388748, 0.06698080152273178, 0.01534315012395382, -0.0035003034863620996, 0.0477488674223423, 0.0771375447511673, -0.0039025049190968275, 0.0128960395231843, 0.014851052314043045, -0.020391808822751045, -0.03583855181932449, 0.013087611645460129, 0.03157813102006912, -0.009812369011342525, -0.005771242082118988, -0.039796724915504456, 0.058492135256528854, 0.010058850049972534, 0.009624219499528408, -0.03226517140865326, -0.01633772812783718, -0.017044594511389732, 0.00885181687772274, 0.040610745549201965, -0.05215835943818092, 0.018253304064273834, 0.019749760627746582, -0.0624222606420517, 0.0013838361483067274, 0.00789985153824091, -0.007208750117570162, 0.060814883559942245, -0.06515383720397949, -0.02668341062963009, -0.02707558125257492, 0.03758999705314636, -0.031866468489170074, -0.019413091242313385, -0.014040515758097172, -0.07637560367584229, -0.06763732433319092, 0.014566159807145596, 0.0018759215017780662, 0.042153630405664444, 0.00011133428051834926, 0.03785594180226326, 0.004827913828194141, -0.004633964039385319, -0.019585253670811653, -0.024013692513108253, -0.001827763975597918, 0.012458302080631256, -0.048840273171663284, -0.015537630766630173, -0.006514102220535278, -0.007617837283760309, 0.008782691322267056, 0.02444581128656864, -0.08387117087841034, -0.05951971188187599, -0.031043175607919693, 0.0633687824010849, 0.07634028792381287, -0.0655369982123375, 0.04030422493815422, 0.0321747325360775, 0.006676067598164082, 0.03004561737179756, -0.039634913206100464, 0.02940131537616253, 0.04484523832798004, 0.027690844610333443, 0.06472502648830414, -0.011453426443040371, -0.019245654344558716, 0.021138686686754227, -0.007994243875145912, -0.12748241424560547, 0.01602885127067566, -0.004318325314670801, 0.04177815094590187, 0.14382871985435486, -0.03180604800581932, -0.009624983184039593, -0.004307655617594719, -0.0010795685229822993, -0.009000812657177448, 0.011630519293248653, -0.0045122746378183365, 0.004401573445647955, -0.005314397159963846, 0.04846665635704994, 0.02988128550350666, 0.00010168794688070193, 0.00637282058596611, -0.030033277347683907, -0.02432919852435589, 0.0015478964196518064, -0.04577043280005455, 0.03673132136464119, -0.005203223321586847, -0.021395836025476456, -0.010620733723044395, -0.06801322102546692, 0.02596299722790718, -0.0203146580606699, -0.01789969950914383, 0.04108935222029686, 0.01290958747267723, -0.01385150570422411, -0.06397227942943573, -0.02415919117629528, -0.04727654531598091, 0.008647428825497627, 0.05393195524811745, 0.00876647885888815, -0.015887202695012093, -0.03329489007592201, 0.013314614072442055, 0.03898732736706734, -0.03474341705441475, 0.00652778847143054, -0.05887483060359955, -0.004332782234996557, -0.05363928899168968, -0.012289420701563358, 0.005105690564960241, -0.012464948929846287, -0.012246882542967796, -0.06791426241397858, -0.05489908531308174, 0.01225333008915186, -0.005543735809624195, -0.011660981923341751, -0.055037032812833786, 0.007509719580411911, 0.04118289798498154, -0.0024771823082119226, -0.04389667883515358, 0.07437130808830261, -0.011294892057776451, -0.008005352690815926, -0.042912326753139496, 0.014755655080080032, -0.009042664431035519, -0.02835916168987751, 0.005731670651584864, -0.019917430356144905, -0.002091140951961279, -0.0095939040184021, 0.02509123831987381, -0.0018456003163009882, 0.03867942467331886, -0.024881424382328987, 0.019402340054512024, 0.02429165691137314, 0.014279006980359554, 0.007802673149853945, 0.04736911132931709, 0.00822100043296814, -0.036976996809244156]'

In [149]:
df[df['item_name'].isnull()]

,sample_id,catalog_content,image_link,item_name,value,unit,pack,unit_clean,text_embeddings,image_embeddings,extra_attributes
17074,43756,"item name 1: ovaltine original add milk 800g, ...",https://m.media-amazon.com/images/I/61CsamBdfx...,NaN,169.31,ounce,1,ounce,"[-0.008718821220099926, -0.0637810081243515, -...","[-0.015361707657575607, 0.03299618139863014, -...","nutritious, satisfying, classic, rich"
25975,22108,item name 1: item# 710-4093\nitem name 2: nonp...,https://m.media-amazon.com/images/I/616cg7ff-V...,NaN,1.00,count,1,count,"[-0.01837625354528427, -0.019201157614588737, ...","[0.018961524590849876, -0.022920291870832443, ...",NaN
42916,150157,item name 1: item# 610-208\nitem name 2: icing...,https://m.media-amazon.com/images/I/81d9AFW53D...,NaN,1.00,ounce,1,ounce,"[0.004371924791485071, -0.04087495803833008, -...","[0.04138248413801193, -0.012088080868124962, 0...",NaN
47329,50844,item name 1: item# 2115-3834\nitem name 2: suc...,https://m.media-amazon.com/images/I/512B-b-qiR...,NaN,NaN,none,1,none,"[-0.05843573063611984, -0.035252880305051804, ...","[-0.01158262137323618, 0.011427353136241436, -...",NaN
49740,262412,item name 1: twinings everyday - 80 per pack (...,https://m.media-amazon.com/images/I/81SBr8hCx6...,NaN,80.00,count,1,count,"[-0.03631456196308136, -0.013251075521111488, ...","[0.0037055080756545067, 0.04995265603065491, -...",NaN
55240,87303,item name 1: item# 704-1019\nitem name 2: spar...,https://m.media-amazon.com/images/I/71t4yOj-1F...,NaN,1.00,ounce,1,ounce,"[0.022335415706038475, -0.013346511870622635, ...","[0.051684942096471786, -0.029502492398023605, ...",NaN
60840,271976,item name 1: item# 704-1061\nitem name 2: spar...,https://m.media-amazon.com/images/I/61DUu7f7mL...,NaN,3.50,fl oz,1,fl oz,"[-0.04830523952841759, -0.03989945352077484, -...","[0.04461781680583954, -0.00849824771285057, -0...",NaN
61088,89935,item name 1: walkers shortbread festive shapes...,https://m.media-amazon.com/images/I/71yiBs1zuV...,NaN,1.00,count,1,count,"[0.020459065213799477, -0.04255726560950279, 0...","[0.009919802658259869, -0.007396154571324587, ...",NaN

In [150]:
# df = df.dropna()

In [151]:
df.isnull().sum()

sample_id               0
catalog_content         0
image_link              0
item_name               8
value                1011
unit                    0
pack                    0
unit_clean              0
text_embeddings         0
image_embeddings        0
extra_attributes    31080
dtype: int64

In [152]:
# import pandas as pd

# # Select only rows where 'value' is null
# missing_value_rows = df[df['value'].isna()]

# # Save them to a CSV file
# missing_value_rows.to_csv("rows_with_missing_value_testtttttttt.csv", index=False)

# print("✅ Saved rows with missing 'value' to 'rows_with_missing_value.csv'")
# print("Shape:", missing_value_rows.shape)

In [153]:
# Fill missing values in extra_attributes with "none"
df['extra_attributes'] = df['extra_attributes'].fillna("none")

# Optional: also replace empty strings just in case
df['extra_attributes'] = df['extra_attributes'].replace("", "none")

# Check again
print(df['extra_attributes'].isna().sum())

0

In [154]:
df.isnull().sum()

sample_id              0
catalog_content        0
image_link             0
item_name              8
value               1011
unit                   0
pack                   0
unit_clean             0
text_embeddings        0
image_embeddings       0
extra_attributes       0
dtype: int64

In [155]:
df_withoutcatalog = df.drop('catalog_content', axis=1)  # axis=1 means columns

In [156]:
df_withoutcatalog.head()

,sample_id,image_link,item_name,value,unit,pack,unit_clean,text_embeddings,image_embeddings,extra_attributes
0,100179,https://m.media-amazon.com/images/I/71hoAn78AW...,rani 14-spice eshamaya's mango chutney (indian...,10.5,ounce,1,ounce,"[0.036331795156002045, -0.052913691848516464, ...","[0.009049994871020317, 0.00274485326372087, -0...","vegan, non-gmo, premium, gourmet"
1,245611,https://m.media-amazon.com/images/I/61ex8NHCIj...,natural milk tea flavoring extract by halo pan...,2.0,fl oz,1,fl oz,"[-0.01868608593940735, -0.013683686032891273, ...","[0.014290607534348965, -0.04910419136285782, 0...","dye-free, gourmet, gluten-free, dairy-free, so..."
2,146263,https://m.media-amazon.com/images/I/61KCM61J8e...,honey filled hard candy - bulk pack 2 pounds -...,32.0,ounce,1,ounce,"[0.07000485807657242, -0.06418927758932114, -0...","[-0.010892418213188648, -0.038370147347450256,...",none
3,95658,https://m.media-amazon.com/images/I/51Ex6uOH7y...,vlasic snack'mm's kosher dill 16 oz (pack of 2),2.0,count,2,count,"[-0.04193189740180969, -0.02518327534198761, 0...","[0.058143433183431625, -0.004104044754058123, ...",none
4,36806,https://m.media-amazon.com/images/I/71QYlrOMoS...,"mccormick culinary vanilla extract, 32 fl oz -...",32.0,fl oz,1,fl oz,"[0.021312430500984192, 0.0017853323370218277, ...","[-0.035538848489522934, 0.009405052289366722, ...","non-gmo, pure, premium, satisfying, fragrant, ..."

In [157]:
df_withoutimglnk = df_withoutcatalog.drop('image_link', axis=1)  # axis=1 means columns

In [158]:
df_withoutimglnk.head()

,sample_id,item_name,value,unit,pack,unit_clean,text_embeddings,image_embeddings,extra_attributes
0,100179,rani 14-spice eshamaya's mango chutney (indian...,10.5,ounce,1,ounce,"[0.036331795156002045, -0.052913691848516464, ...","[0.009049994871020317, 0.00274485326372087, -0...","vegan, non-gmo, premium, gourmet"
1,245611,natural milk tea flavoring extract by halo pan...,2.0,fl oz,1,fl oz,"[-0.01868608593940735, -0.013683686032891273, ...","[0.014290607534348965, -0.04910419136285782, 0...","dye-free, gourmet, gluten-free, dairy-free, so..."
2,146263,honey filled hard candy - bulk pack 2 pounds -...,32.0,ounce,1,ounce,"[0.07000485807657242, -0.06418927758932114, -0...","[-0.010892418213188648, -0.038370147347450256,...",none
3,95658,vlasic snack'mm's kosher dill 16 oz (pack of 2),2.0,count,2,count,"[-0.04193189740180969, -0.02518327534198761, 0...","[0.058143433183431625, -0.004104044754058123, ...",none
4,36806,"mccormick culinary vanilla extract, 32 fl oz -...",32.0,fl oz,1,fl oz,"[0.021312430500984192, 0.0017853323370218277, ...","[-0.035538848489522934, 0.009405052289366722, ...","non-gmo, pure, premium, satisfying, fragrant, ..."

In [159]:
# df_withoutprice = df_withoutimglnk.drop('price', axis=1)  # axis=1 means columns

In [160]:
df_withoutprice=df_withoutimglnk

In [161]:
df_withoutprice.head()

,sample_id,item_name,value,unit,pack,unit_clean,text_embeddings,image_embeddings,extra_attributes
0,100179,rani 14-spice eshamaya's mango chutney (indian...,10.5,ounce,1,ounce,"[0.036331795156002045, -0.052913691848516464, ...","[0.009049994871020317, 0.00274485326372087, -0...","vegan, non-gmo, premium, gourmet"
1,245611,natural milk tea flavoring extract by halo pan...,2.0,fl oz,1,fl oz,"[-0.01868608593940735, -0.013683686032891273, ...","[0.014290607534348965, -0.04910419136285782, 0...","dye-free, gourmet, gluten-free, dairy-free, so..."
2,146263,honey filled hard candy - bulk pack 2 pounds -...,32.0,ounce,1,ounce,"[0.07000485807657242, -0.06418927758932114, -0...","[-0.010892418213188648, -0.038370147347450256,...",none
3,95658,vlasic snack'mm's kosher dill 16 oz (pack of 2),2.0,count,2,count,"[-0.04193189740180969, -0.02518327534198761, 0...","[0.058143433183431625, -0.004104044754058123, ...",none
4,36806,"mccormick culinary vanilla extract, 32 fl oz -...",32.0,fl oz,1,fl oz,"[0.021312430500984192, 0.0017853323370218277, ...","[-0.035538848489522934, 0.009405052289366722, ...","non-gmo, pure, premium, satisfying, fragrant, ..."

In [162]:
data=df_withoutprice

In [163]:
data.head()

,sample_id,item_name,value,unit,pack,unit_clean,text_embeddings,image_embeddings,extra_attributes
0,100179,rani 14-spice eshamaya's mango chutney (indian...,10.5,ounce,1,ounce,"[0.036331795156002045, -0.052913691848516464, ...","[0.009049994871020317, 0.00274485326372087, -0...","vegan, non-gmo, premium, gourmet"
1,245611,natural milk tea flavoring extract by halo pan...,2.0,fl oz,1,fl oz,"[-0.01868608593940735, -0.013683686032891273, ...","[0.014290607534348965, -0.04910419136285782, 0...","dye-free, gourmet, gluten-free, dairy-free, so..."
2,146263,honey filled hard candy - bulk pack 2 pounds -...,32.0,ounce,1,ounce,"[0.07000485807657242, -0.06418927758932114, -0...","[-0.010892418213188648, -0.038370147347450256,...",none
3,95658,vlasic snack'mm's kosher dill 16 oz (pack of 2),2.0,count,2,count,"[-0.04193189740180969, -0.02518327534198761, 0...","[0.058143433183431625, -0.004104044754058123, ...",none
4,36806,"mccormick culinary vanilla extract, 32 fl oz -...",32.0,fl oz,1,fl oz,"[0.021312430500984192, 0.0017853323370218277, ...","[-0.035538848489522934, 0.009405052289366722, ...","non-gmo, pure, premium, satisfying, fragrant, ..."

In [164]:
import numpy as np

In [165]:
from sentence_transformers import SentenceTransformer

print("\n🔹 Generating text embeddings...")

# Load model (CPU or GPU)
device = "cuda"  # or "cpu"
text_model = SentenceTransformer("all-MiniLM-L12-v2", device=device)

# Convert item_name column to list of strings
brand_texts = data["item_name"].astype(str).tolist()

# Generate embeddings
brand_text_embeddings = text_model.encode(
    brand_texts,
    batch_size=64,
    show_progress_bar=True
)

# Save embeddings into the DataFrame
data["item_name_embeddings"] = list(brand_text_embeddings)

np.save("test_brand_embeddings_s2.npy", brand_text_embeddings)

# Optional: Check the first few rows
print(data.head())

🔹 Generating text embeddings...

Batches: 100%|██████████| 1172/1172 [00:45<00:00, 25.56it/s]

   sample_id                                          item_name  value   unit  \
0     100179  rani 14-spice eshamaya's mango chutney (indian...   10.5  ounce
1     245611  natural milk tea flavoring extract by halo pan...    2.0  fl oz
2     146263  honey filled hard candy - bulk pack 2 pounds -...   32.0  ounce
3      95658    vlasic snack'mm's kosher dill 16 oz (pack of 2)    2.0  count
4      36806  mccormick culinary vanilla extract, 32 fl oz -...   32.0  fl oz

   pack unit_clean                                    text_embeddings  \
0     1      ounce  [0.036331795156002045, -0.052913691848516464, ...
1     1      fl oz  [-0.01868608593940735, -0.013683686032891273, ...
2     1      ounce  [0.07000485807657242, -0.06418927758932114, -0...
3     2      count  [-0.04193189740180969, -0.02518327534198761, 0...
4     1      fl oz  [0.021312430500984192, 0.0017853323370218277, ...

                                    image_embeddings  \
0  [0.009049994871020317, 0.00274485326372087, -0...
1  [0.014290607534348965, -0.04910419136285782, 0...
2  [-0.010892418213188648, -0.038370147347450256,...
3  [0.058143433183431625, -0.004104044754058123, ...
4  [-0.035538848489522934, 0.009405052289366722, ...

                                    extra_attributes  \
0                   vegan, non-gmo, premium, gourmet
1  dye-free, gourmet, gluten-free, dairy-free, so...
2                                               none
3                                               none
4  non-gmo, pure, premium, satisfying, fragrant, ...

                                item_name_embeddings
0  [0.010695033, -0.011938255, -0.038903236, 0.04...
1  [-0.045415778, -0.05733894, 0.06405218, 0.0303...
2  [-0.038928892, 0.021900626, 0.026193727, 0.018...
3  [-0.015539844, 0.021211259, -0.045587268, -0.0...
4  [-0.027185516, -0.0367115, -0.006675318, 0.009...

In [166]:
data.head()

,sample_id,item_name,value,unit,pack,unit_clean,text_embeddings,image_embeddings,extra_attributes,item_name_embeddings
0,100179,rani 14-spice eshamaya's mango chutney (indian...,10.5,ounce,1,ounce,"[0.036331795156002045, -0.052913691848516464, ...","[0.009049994871020317, 0.00274485326372087, -0...","vegan, non-gmo, premium, gourmet","[0.010695033, -0.011938255, -0.038903236, 0.04..."
1,245611,natural milk tea flavoring extract by halo pan...,2.0,fl oz,1,fl oz,"[-0.01868608593940735, -0.013683686032891273, ...","[0.014290607534348965, -0.04910419136285782, 0...","dye-free, gourmet, gluten-free, dairy-free, so...","[-0.045415778, -0.05733894, 0.06405218, 0.0303..."
2,146263,honey filled hard candy - bulk pack 2 pounds -...,32.0,ounce,1,ounce,"[0.07000485807657242, -0.06418927758932114, -0...","[-0.010892418213188648, -0.038370147347450256,...",none,"[-0.038928892, 0.021900626, 0.026193727, 0.018..."
3,95658,vlasic snack'mm's kosher dill 16 oz (pack of 2),2.0,count,2,count,"[-0.04193189740180969, -0.02518327534198761, 0...","[0.058143433183431625, -0.004104044754058123, ...",none,"[-0.015539844, 0.021211259, -0.045587268, -0.0..."
4,36806,"mccormick culinary vanilla extract, 32 fl oz -...",32.0,fl oz,1,fl oz,"[0.021312430500984192, 0.0017853323370218277, ...","[-0.035538848489522934, 0.009405052289366722, ...","non-gmo, pure, premium, satisfying, fragrant, ...","[-0.027185516, -0.0367115, -0.006675318, 0.009..."

In [167]:
data2 = data.drop('item_name', axis=1)  # axis=1 means columns

In [168]:
data2.head()

,sample_id,value,unit,pack,unit_clean,text_embeddings,image_embeddings,extra_attributes,item_name_embeddings
0,100179,10.5,ounce,1,ounce,"[0.036331795156002045, -0.052913691848516464, ...","[0.009049994871020317, 0.00274485326372087, -0...","vegan, non-gmo, premium, gourmet","[0.010695033, -0.011938255, -0.038903236, 0.04..."
1,245611,2.0,fl oz,1,fl oz,"[-0.01868608593940735, -0.013683686032891273, ...","[0.014290607534348965, -0.04910419136285782, 0...","dye-free, gourmet, gluten-free, dairy-free, so...","[-0.045415778, -0.05733894, 0.06405218, 0.0303..."
2,146263,32.0,ounce,1,ounce,"[0.07000485807657242, -0.06418927758932114, -0...","[-0.010892418213188648, -0.038370147347450256,...",none,"[-0.038928892, 0.021900626, 0.026193727, 0.018..."
3,95658,2.0,count,2,count,"[-0.04193189740180969, -0.02518327534198761, 0...","[0.058143433183431625, -0.004104044754058123, ...",none,"[-0.015539844, 0.021211259, -0.045587268, -0.0..."
4,36806,32.0,fl oz,1,fl oz,"[0.021312430500984192, 0.0017853323370218277, ...","[-0.035538848489522934, 0.009405052289366722, ...","non-gmo, pure, premium, satisfying, fragrant, ...","[-0.027185516, -0.0367115, -0.006675318, 0.009..."

In [169]:
data2["unit"].unique()

array(['ounce', 'fl oz', 'count', 'oz', 'none', 'each', 'fl. oz', 'box',
       'pound', 'packs', 'pack', 'milliliter', 'fluid ounce',
       '200 capsules - packed bulk 20 packs of 10 capsules per vacuum sealed pouch',
       'gram', 'packet', 'product_weight', 'grams', 'lb', '1', 'kit',
       'na', 'fluid_ounces', 'kg', 'tea bags', 'liters', 'ct',
       'millilitro', '2', 'bag', 'ounces', 'each / pack: 1', 'container',
       'pac', 'milliliters', 'foot', 'paper cupcake liners', '16 ounces',
       'millilitre', 'k-cups', 'm', 'sq ft', 'bottle', 'fluid ounces',
       'g', '0.7 lbs</p>', 'ltr', 'ea', 'ml', '....', '1.76 ounce',
       'unit', 'sachet', '(pack of 1)', 'per package', 'jar', 'tin',
       'liter', 'lbs', 'pieces', 'piece', 'case / pack: 6', 'fl ounce',
       'gallon', 'jars', 'count / count', 'gallons', 'pounds', 'fl.oz',
       'cou', 'sugar substitute', 'pouch', 'capsules', 'stück',
       'comes as a single dispenser unit with 1 count of candy refills',
       'fluid ounce(s)', '12.54', '16.9 oz', 'mililitro'], dtype=object)

In [170]:
# Count occurrences
unit_counts = data2["unit"].value_counts()

# Convert to DataFrame
unit_counts_df = unit_counts.reset_index()
unit_counts_df.columns = ['unit', 'count']

# Show all rows
pd.set_option('display.max_rows', None)
print(unit_counts_df)

                                                 unit  count
0                                               ounce  42884
1                                               count  18187
2                                               fl oz  11348
3                                                  oz   1019
4                                                none   1011
5                                               pound    200
6                                                  ct     39
7                                                gram     30
8                                         fluid ounce     25
9                                              fl. oz     25
10                                               pack     21
11                                                 lb     18
12                                               each     17
13                                              packs     15
14                                             ounces     13
15                                             bottle      9
16                                             liters      7
17                                         millilitre      7
18                                                bag      7
19                                     each / pack: 1      6
20                                       fluid ounces      6
21                                         milliliter      6
22                                                box      5
23                                              grams      5
24                                     product_weight      5
25                                                  1      5
26                                           tea bags      4
27                                                jar      4
28                                               foot      4
29                               paper cupcake liners      3
30                                             k-cups      3
31                                                 ea      3
32                                                 ml      3
33                                             packet      3
34                                             gallon      2
35                                        per package      2
36                                                 kg      2
37                                              sq ft      2
38                                                pac      2
39                                              piece      2
40                                     fluid ounce(s)      2
41                                                lbs      2
42  200 capsules - packed bulk 20 packs of 10 caps...      1
43                                                kit      1
44                                                  2      1
45                                                 na      1
46                                       fluid_ounces      1
47                                                ltr      1
48                                        0.7 lbs</p>      1
49                                                  g      1
50                                                  m      1
51                                        milliliters      1
52                                          container      1
53                                          16 ounces      1
54                                         millilitro      1
55                                        (pack of 1)      1
56                                             sachet      1
57                                               unit      1
58                                                tin      1
59                                              liter      1
60                                             pieces      1
61                                         1.76 ounce      1
62                                               ....      1
63                                           fl ounce      1
64                                     case / pack: 6      1
65                                      count / count      1
66                                               jars      1
67                                             pounds      1
68                                              fl.oz      1
69                                                cou      1
70                                            gallons      1
71                                   sugar substitute      1
72                                              pouch      1
73                                              stück      1
74                                           capsules      1
75  comes as a single dispenser unit with 1 count ...      1
76                                              12.54      1
77                                            16.9 oz      1
78                                          mililitro      1

In [171]:
# Filter rows where unit is "count"
count_rows = data2[data2["unit"] == "count"]

# Show the first few rows
count_rows.head()

,sample_id,value,unit,pack,unit_clean,text_embeddings,image_embeddings,extra_attributes,item_name_embeddings
3,95658,2.0,count,2,count,"[-0.04193189740180969, -0.02518327534198761, 0...","[0.058143433183431625, -0.004104044754058123, ...",none,"[-0.015539844, 0.021211259, -0.045587268, -0.0..."
7,3780,1.0,count,1,count,"[-0.023272138088941574, -0.06071946397423744, ...","[0.016048552468419075, -0.016859684139490128, ...","pure, rich","[-0.05258572, 0.0014832151, 0.016793791, 0.052..."
12,20801,75.0,count,1,count,"[-0.018269607797265053, 0.025456957519054413, ...","[-0.002668810775503516, 0.005417943000793457, ...","caffeine-free, premium","[-0.05977059, 0.005761851, 0.0018754648, 0.009..."
16,3342,12.0,count,12,count,"[-0.004821034613996744, -0.054484497755765915,...","[-0.05796224996447563, -0.04786765202879906, 0...",none,"[-0.0073384186, 0.0151219675, -0.055941306, 0...."
17,115635,1.0,count,1,count,"[-0.00867491401731968, 0.008178234100341797, -...","[-0.005814038682729006, -0.012875690124928951,...",none,"[-0.04386103, -0.013083418, 0.070017576, -0.02..."

In [172]:
import pandas as pd

# Example: your dataset
# data2 = pd.read_csv("your_dataset.csv")

# Conversion constants
ML_TO_FLOZ = 0.033814   # 1 mL = 0.033814 fl oz
L_TO_FLOZ = 33.814      # 1 liter = 33.814 fl oz
GRAM_TO_LB = 0.00220462 # 1 gram = 0.00220462 pound
KG_TO_LB = 2.20462      # 1 kg = 2.20462 pound

def normalize_units(row):
    unit = str(row['unit']).lower().strip()
    value = row['value']

    # -----------------------------
    # COUNTABLE UNITS
    # -----------------------------
    if unit in ['count', 'ct', 'each', 'pack', 'packs', 'piece', 'each / pack: 1']:
        return value, 'count'

    # -----------------------------
    # WEIGHT UNITS
    # -----------------------------
    elif unit in ['oz', 'ounce', 'ounces']:
        return value, 'oz'
    elif unit in ['pound', 'lb', 'lbs', 'pounds']:
        return value, 'pound'
    elif unit in ['gram', 'grams', 'gramm', 'g']:
        return value * GRAM_TO_LB, 'pound'
    elif unit in ['kg', 'kilogram', 'kilograms']:
        return value * KG_TO_LB, 'pound'

    # -----------------------------
    # LIQUID UNITS → convert all to fl oz
    # -----------------------------
    elif unit in ['fl oz', 'fl. oz', 'fluid ounce', 'fluid ounces', 'fluid ounce(s)']:
        return value, 'fl oz'
    elif unit in ['ml', 'milliliter', 'milliliters', 'millilitre', 'millilitres', 'mililitro']:
        return value * ML_TO_FLOZ, 'fl oz'
    elif unit in ['l', 'ltr', 'liter', 'liters']:
        return value * L_TO_FLOZ, 'fl oz'

    # -----------------------------
    # DEFAULT: leave as-is (optional)
    # -----------------------------
    else:
        return value, unit

# Apply the function
data2[['value_normalized', 'unit_normalized']] = data2.apply(
    normalize_units, axis=1, result_type='expand'
)

# Optional: check results
print(data2[['unit', 'value', 'unit_normalized', 'value_normalized']].head(20))

     unit  value unit_normalized  value_normalized
0   ounce   10.5              oz              10.5
1   fl oz    2.0           fl oz               2.0
2   ounce   32.0              oz              32.0
3   count    2.0           count               2.0
4   fl oz   32.0           fl oz              32.0
5   ounce   16.0              oz              16.0
6   ounce   45.0              oz              45.0
7   count    1.0           count               1.0
8      oz  180.0              oz             180.0
9   ounce   18.0              oz              18.0
10  ounce   48.0              oz              48.0
11  ounce  192.0              oz             192.0
12  count   75.0           count              75.0
13  ounce    7.0              oz               7.0
14  ounce    1.0              oz               1.0
15  ounce    9.0              oz               9.0
16  count   12.0           count              12.0
17  count    1.0           count               1.0
18  ounce   22.0              oz              22.0
19  ounce  192.0              oz             192.0

In [173]:
# Count occurrences
norm_unit_counts = data2["unit_normalized"].value_counts()

# Convert to DataFrame
norm_unit_counts_df = norm_unit_counts.reset_index()
norm_unit_counts_df.columns = ['unit', 'count']

# Show all rows
pd.set_option('display.max_rows', None)
print(norm_unit_counts_df)

                                                 unit  count
0                                                  oz  43916
1                                               count  18287
2                                               fl oz  11433
3                                                none   1011
4                                               pound    259
5                                              bottle      9
6                                                 bag      7
7                                                   1      5
8                                      product_weight      5
9                                                 box      5
10                                               foot      4
11                                           tea bags      4
12                                                jar      4
13                                                 ea      3
14                               paper cupcake liners      3
15                                             k-cups      3
16                                             packet      3
17                                                pac      2
18                                              sq ft      2
19                                        per package      2
20                                             gallon      2
21                                          container      1
22                                         millilitro      1
23                                       fluid_ounces      1
24                                                kit      1
25  200 capsules - packed bulk 20 packs of 10 caps...      1
26                                                 na      1
27                                                  2      1
28                                        0.7 lbs</p>      1
29                                                  m      1
30                                               ....      1
31                                         1.76 ounce      1
32                                             sachet      1
33                                               unit      1
34                                        (pack of 1)      1
35                                          16 ounces      1
36                                                tin      1
37                                             pieces      1
38                                     case / pack: 6      1
39                                           fl ounce      1
40                                               jars      1
41                                      count / count      1
42                                            gallons      1
43                                              fl.oz      1
44                                                cou      1
45                                   sugar substitute      1
46                                              pouch      1
47                                           capsules      1
48                                              stück      1
49  comes as a single dispenser unit with 1 count ...      1
50                                              12.54      1
51                                            16.9 oz      1

In [174]:
data2.head()

,sample_id,value,unit,pack,unit_clean,text_embeddings,image_embeddings,extra_attributes,item_name_embeddings,value_normalized,unit_normalized
0,100179,10.5,ounce,1,ounce,"[0.036331795156002045, -0.052913691848516464, ...","[0.009049994871020317, 0.00274485326372087, -0...","vegan, non-gmo, premium, gourmet","[0.010695033, -0.011938255, -0.038903236, 0.04...",10.5,oz
1,245611,2.0,fl oz,1,fl oz,"[-0.01868608593940735, -0.013683686032891273, ...","[0.014290607534348965, -0.04910419136285782, 0...","dye-free, gourmet, gluten-free, dairy-free, so...","[-0.045415778, -0.05733894, 0.06405218, 0.0303...",2.0,fl oz
2,146263,32.0,ounce,1,ounce,"[0.07000485807657242, -0.06418927758932114, -0...","[-0.010892418213188648, -0.038370147347450256,...",none,"[-0.038928892, 0.021900626, 0.026193727, 0.018...",32.0,oz
3,95658,2.0,count,2,count,"[-0.04193189740180969, -0.02518327534198761, 0...","[0.058143433183431625, -0.004104044754058123, ...",none,"[-0.015539844, 0.021211259, -0.045587268, -0.0...",2.0,count
4,36806,32.0,fl oz,1,fl oz,"[0.021312430500984192, 0.0017853323370218277, ...","[-0.035538848489522934, 0.009405052289366722, ...","non-gmo, pure, premium, satisfying, fragrant, ...","[-0.027185516, -0.0367115, -0.006675318, 0.009...",32.0,fl oz

In [175]:
final_data=data2.drop(columns=['unit', 'unit_clean', 'value'])

In [191]:
# Define liquid and count units
liquid_units = ["fl.oz", "fl oz", "fl ounce","fl. oz.","fluid_ounces",]  # normalize to "fl oz"
count_units = [
    "bottle", "can", "bag", "jar", "per carton", "k-cups","tin","sachet","cou",
    "pouch", "tea bags", "paper cupcake liners", "1", "box","unit","2","pac","jars","pieces","count / count","stück","comes as a single dispenser unit with 1 count ...","(pack of 1)"
    "ziplock bags", "carton" , "bottles","bucket","units","8","24","per package","comes as a single 0.1 oz stick for on-the-go use","container","packet","kit","12.54","case / pack: 6"
]
oz=["product_weight","oz.","20 oz.","16.9 oz","1.76 ounce","16 ounces"]

# Function to normalize units
def normalize_unit(x):
    if pd.isna(x):
        return None
    x = str(x).lower().strip()
    
    # Normalize specific liquid units
    if x in liquid_units:
        return "fl oz"
    
    # Map other units to 'count'
    elif x in count_units:
        return "count"

    # Map other units to 'count'
    elif x in oz:
        return "oz"
    
    # Otherwise keep original
    else:
        return x

# Apply normalization
final_data['unit_normalized'] = final_data['unit_normalized'].apply(normalize_unit)

# Optional: check results
print(final_data[['unit_normalized']].head(20))

   unit_normalized
0               oz
1            fl oz
2               oz
3            count
4            fl oz
5               oz
6               oz
7            count
8               oz
9               oz
10              oz
11              oz
12           count
13              oz
14              oz
15              oz
16           count
17           count
18              oz
19              oz

In [192]:
# Count occurrences
norm_unit_counts =final_data["unit_normalized"].value_counts()

# Convert to DataFrame
norm_unit_counts_df = norm_unit_counts.reset_index()
norm_unit_counts_df.columns = ['unit', 'count']

# Show all rows
pd.set_option('display.max_rows', None)
print(norm_unit_counts_df)

                                                 unit  count
0                                                  oz  43923
1                                               count  18348
2                                               fl oz  11437
3                                                none   1011
4                                               pound    259
5                                                foot      4
6                                                  ea      3
7                                               sq ft      2
8                                              gallon      2
9                                                  na      1
10                                         millilitro      1
11  200 capsules - packed bulk 20 packs of 10 caps...      1
12                                        0.7 lbs</p>      1
13                                                  m      1
14                                               ....      1
15                                        (pack of 1)      1
16                                            gallons      1
17                                   sugar substitute      1
18                                           capsules      1
19  comes as a single dispenser unit with 1 count ...      1

In [193]:
import torch
import torch.nn as nn

# Map unit to index
unit_encoder = {unit: i for i, unit in enumerate(final_data['unit_normalized'].unique())}

# Create unit_idx in final_data
final_data['unit_idx'] = final_data['unit_normalized'].map(unit_encoder)

# PyTorch embedding layer
num_units = len(unit_encoder)      # 3 in your case
embedding_dim = 4                  # small number since only 3 units
embedding_layer = nn.Embedding(num_units, embedding_dim)

# Convert to tensor
unit_tensor = torch.tensor(final_data['unit_idx'].values, dtype=torch.long)

# Get embeddings
unit_embedded = embedding_layer(unit_tensor)  # shape: [num_rows, embedding_dim]

In [194]:
final_data.head()

,sample_id,pack,text_embeddings,image_embeddings,extra_attributes,brand_product_embedding,value_normalized,unit_normalized,unit_idx
0,100179,1,"[0.036331795156002045, -0.052913691848516464, ...","[0.009049994871020317, 0.00274485326372087, -0...","vegan, non-gmo, premium, gourmet","[0.010695033, -0.011938255, -0.038903236, 0.04...",10.5,oz,0
1,245611,1,"[-0.01868608593940735, -0.013683686032891273, ...","[0.014290607534348965, -0.04910419136285782, 0...","dye-free, gourmet, gluten-free, dairy-free, so...","[-0.045415778, -0.05733894, 0.06405218, 0.0303...",2.0,fl oz,1
2,146263,1,"[0.07000485807657242, -0.06418927758932114, -0...","[-0.010892418213188648, -0.038370147347450256,...",none,"[-0.038928892, 0.021900626, 0.026193727, 0.018...",32.0,oz,0
3,95658,2,"[-0.04193189740180969, -0.02518327534198761, 0...","[0.058143433183431625, -0.004104044754058123, ...",none,"[-0.015539844, 0.021211259, -0.045587268, -0.0...",2.0,count,2
4,36806,1,"[0.021312430500984192, 0.0017853323370218277, ...","[-0.035538848489522934, 0.009405052289366722, ...","non-gmo, pure, premium, satisfying, fragrant, ...","[-0.027185516, -0.0367115, -0.006675318, 0.009...",32.0,fl oz,1

In [195]:
final_data.rename(columns={'item_name_embeddings': 'brand_product_embedding'}, inplace=True)

In [196]:
final_data = final_data[[
    'sample_id',
    'text_embeddings',
    'image_embeddings',
    'brand_product_embedding',
    'value_normalized',
    'unit_idx',
    'extra_attributes',
    'pack',
]]

In [197]:
final_data.head()

,sample_id,text_embeddings,image_embeddings,brand_product_embedding,value_normalized,unit_idx,extra_attributes,pack
0,100179,"[0.036331795156002045, -0.052913691848516464, ...","[0.009049994871020317, 0.00274485326372087, -0...","[0.010695033, -0.011938255, -0.038903236, 0.04...",10.5,0,"vegan, non-gmo, premium, gourmet",1
1,245611,"[-0.01868608593940735, -0.013683686032891273, ...","[0.014290607534348965, -0.04910419136285782, 0...","[-0.045415778, -0.05733894, 0.06405218, 0.0303...",2.0,1,"dye-free, gourmet, gluten-free, dairy-free, so...",1
2,146263,"[0.07000485807657242, -0.06418927758932114, -0...","[-0.010892418213188648, -0.038370147347450256,...","[-0.038928892, 0.021900626, 0.026193727, 0.018...",32.0,0,none,1
3,95658,"[-0.04193189740180969, -0.02518327534198761, 0...","[0.058143433183431625, -0.004104044754058123, ...","[-0.015539844, 0.021211259, -0.045587268, -0.0...",2.0,2,none,2
4,36806,"[0.021312430500984192, 0.0017853323370218277, ...","[-0.035538848489522934, 0.009405052289366722, ...","[-0.027185516, -0.0367115, -0.006675318, 0.009...",32.0,1,"non-gmo, pure, premium, satisfying, fragrant, ...",1

In [198]:
# Create total_value feature
final_data['total_value'] = final_data['value_normalized'] * final_data['pack']

# Optional: check first few rows
final_data.head()

,sample_id,text_embeddings,image_embeddings,brand_product_embedding,value_normalized,unit_idx,extra_attributes,pack,total_value
0,100179,"[0.036331795156002045, -0.052913691848516464, ...","[0.009049994871020317, 0.00274485326372087, -0...","[0.010695033, -0.011938255, -0.038903236, 0.04...",10.5,0,"vegan, non-gmo, premium, gourmet",1,10.5
1,245611,"[-0.01868608593940735, -0.013683686032891273, ...","[0.014290607534348965, -0.04910419136285782, 0...","[-0.045415778, -0.05733894, 0.06405218, 0.0303...",2.0,1,"dye-free, gourmet, gluten-free, dairy-free, so...",1,2.0
2,146263,"[0.07000485807657242, -0.06418927758932114, -0...","[-0.010892418213188648, -0.038370147347450256,...","[-0.038928892, 0.021900626, 0.026193727, 0.018...",32.0,0,none,1,32.0
3,95658,"[-0.04193189740180969, -0.02518327534198761, 0...","[0.058143433183431625, -0.004104044754058123, ...","[-0.015539844, 0.021211259, -0.045587268, -0.0...",2.0,2,none,2,4.0
4,36806,"[0.021312430500984192, 0.0017853323370218277, ...","[-0.035538848489522934, 0.009405052289366722, ...","[-0.027185516, -0.0367115, -0.006675318, 0.009...",32.0,1,"non-gmo, pure, premium, satisfying, fragrant, ...",1,32.0

In [199]:
final_data = final_data.drop(columns=['value_normalized', 'pack'])

In [200]:
final_data.head()

,sample_id,text_embeddings,image_embeddings,brand_product_embedding,unit_idx,extra_attributes,total_value
0,100179,"[0.036331795156002045, -0.052913691848516464, ...","[0.009049994871020317, 0.00274485326372087, -0...","[0.010695033, -0.011938255, -0.038903236, 0.04...",0,"vegan, non-gmo, premium, gourmet",10.5
1,245611,"[-0.01868608593940735, -0.013683686032891273, ...","[0.014290607534348965, -0.04910419136285782, 0...","[-0.045415778, -0.05733894, 0.06405218, 0.0303...",1,"dye-free, gourmet, gluten-free, dairy-free, so...",2.0
2,146263,"[0.07000485807657242, -0.06418927758932114, -0...","[-0.010892418213188648, -0.038370147347450256,...","[-0.038928892, 0.021900626, 0.026193727, 0.018...",0,none,32.0
3,95658,"[-0.04193189740180969, -0.02518327534198761, 0...","[0.058143433183431625, -0.004104044754058123, ...","[-0.015539844, 0.021211259, -0.045587268, -0.0...",2,none,4.0
4,36806,"[0.021312430500984192, 0.0017853323370218277, ...","[-0.035538848489522934, 0.009405052289366722, ...","[-0.027185516, -0.0367115, -0.006675318, 0.009...",1,"non-gmo, pure, premium, satisfying, fragrant, ...",32.0

In [201]:
from sentence_transformers import SentenceTransformer
import numpy as np

print("\n🔹 Generating embeddings for extra_attributes...")

# Load model (CPU or GPU)
device = "cuda"  # or "cpu"
text_model = SentenceTransformer("all-MiniLM-L12-v2", device=device)

# Convert extra_attributes column to list of strings
extra_texts = final_data["extra_attributes"].astype(str).tolist()

# Generate embeddings in batch
extra_text_embeddings = text_model.encode(
    extra_texts,
    batch_size=64,           # adjust based on your GPU memory
    show_progress_bar=True,
    convert_to_numpy=True     # outputs numpy array
)

# Save embeddings as a .npy file (optional)
np.save("extra_attributes_embeddings.npy", extra_text_embeddings)

# Add embeddings to DataFrame as list for compatibility
final_data["extra_attributes_emb"] = [emb.tolist() for emb in extra_text_embeddings]

# Optional: Check
print(final_data[["extra_attributes", "extra_attributes_emb"]].head())

🔹 Generating embeddings for extra_attributes...

Batches: 100%|██████████| 1172/1172 [00:16<00:00, 71.95it/s]

                                    extra_attributes  \
0                   vegan, non-gmo, premium, gourmet
1  dye-free, gourmet, gluten-free, dairy-free, so...
2                                               none
3                                               none
4  non-gmo, pure, premium, satisfying, fragrant, ...

                                extra_attributes_emb
0  [0.006856043357402086, 0.008460109122097492, 0...
1  [0.023130862042307854, -0.04696176201105118, 0...
2  [0.0014492346672341228, -0.0001916056789923459...
3  [0.0014492346672341228, -0.0001916056789923459...
4  [-0.03174854442477226, 0.03517179936170578, 0....

In [202]:
final_data = final_data[[
    'sample_id',
    'text_embeddings',
    'image_embeddings',
    'brand_product_embedding',
    'total_value',
    'extra_attributes_emb',
    'unit_idx',
]]

In [203]:
final_data.shape[0]

75000

In [204]:
final_data.to_csv('test_final_dataset_pitstop7486_final_s3.csv')

In [207]:
final_data.head()

,sample_id,text_embeddings,image_embeddings,brand_product_embedding,total_value,unit_idx
0,100179,"[0.036331795156002045, -0.052913691848516464, ...","[0.009049994871020317, 0.00274485326372087, -0...","[0.010695033, -0.011938255, -0.038903236, 0.04...",10.5,0
1,245611,"[-0.01868608593940735, -0.013683686032891273, ...","[0.014290607534348965, -0.04910419136285782, 0...","[-0.045415778, -0.05733894, 0.06405218, 0.0303...",2.0,1
2,146263,"[0.07000485807657242, -0.06418927758932114, -0...","[-0.010892418213188648, -0.038370147347450256,...","[-0.038928892, 0.021900626, 0.026193727, 0.018...",32.0,0
3,95658,"[-0.04193189740180969, -0.02518327534198761, 0...","[0.058143433183431625, -0.004104044754058123, ...","[-0.015539844, 0.021211259, -0.045587268, -0.0...",4.0,2
4,36806,"[0.021312430500984192, 0.0017853323370218277, ...","[-0.035538848489522934, 0.009405052289366722, ...","[-0.027185516, -0.0367115, -0.006675318, 0.009...",32.0,1

In [210]:
# Example: drop columns you don’t need
cols_to_drop = [

    "extra_attributes_emb",
    "text_embeddings",
    "image_embeddings",
    "brand_product_embedding"

]

# Drop them directly from train and test
final_data.drop(columns=cols_to_drop, inplace=True, errors="ignore")


print("✅ Dropped unnecessary columns")
print("Remaining columns in train:", final_data.columns.tolist())

✅ Dropped unnecessary columns
Remaining columns in train: ['sample_id', 'total_value', 'unit_idx']

In [212]:
final_data.to_csv('test_final_dataset_pitstop7486_finale_s3.csv')

In [211]:
final_data.head()

   sample_id  total_value  unit_idx
0     100179         10.5         0
1     245611          2.0         1
2     146263         32.0         0
3      95658          4.0         2
4      36806         32.0         1