In [289]:
print("hi")

hi

In [290]:
import torch
print(torch.__version__)

2.8.0+cu128

In [291]:
import pandas as pd

In [292]:
df=pd.read_csv("final7486_s2.csv")

In [293]:
df.shape[0]

75000

In [294]:
df.head(10)

,sample_id,catalog_content,image_link,price,price_log,item_name,value,unit,pack,unit_clean,text_embeddings,image_embeddings,extra_attributes
0,33127,"item name: la victoria green taco sauce mild, ...",https://m.media-amazon.com/images/I/51mo8htwTH...,4.89,1.587192,"la victoria green taco sauce mild, 12 ounce (p...",72.00,fl oz,6,fl oz,"[0.036331795156002045, -0.052913691848516464, ...","[0.009049994871020317, 0.00274485326372087, -0...",NaN
1,198967,"item name: salerno cookies, the original butte...",https://m.media-amazon.com/images/I/71YtriIHAA...,13.12,2.574138,"salerno cookies, the original butter cookies, ...",32.00,ounce,4,ounce,"[-0.01868608593940735, -0.013683686032891273, ...","[0.014290607534348965, -0.04910419136285782, 0...",classic
2,261251,"item name: bear creek hearty soup bowl, creamy...",https://m.media-amazon.com/images/I/51+PFEe-w-...,1.97,0.678034,"bear creek hearty soup bowl, creamy chicken wi...",11.40,ounce,6,ounce,"[0.07000485807657242, -0.06418927758932114, -0...","[-0.010892418213188648, -0.038370147347450256,...",creamy
3,55858,item name: judee’s blue cheese powder 11.25 oz...,https://m.media-amazon.com/images/I/41mu0HAToD...,30.34,3.412467,judee’s blue cheese powder 11.25 oz - gluten-f...,11.25,ounce,1,ounce,"[-0.04193189740180969, -0.02518327534198761, 0...","[0.058143433183431625, -0.004104044754058123, ...","gluten-free, nut-free"
4,292686,"item name: kedem sherry cooking wine, 12.7 oun...",https://m.media-amazon.com/images/I/41sA037+Qv...,66.49,4.197052,"kedem sherry cooking wine, 12.7 ounce - 12 per...",12.00,count,1,count,"[0.021312430500984192, 0.0017853323370218277, ...","[-0.035538848489522934, 0.009405052289366722, ...",NaN
5,9259,"item name: member's mark member's mark, basil,...",https://m.media-amazon.com/images/I/81nw0HXpCR...,18.50,2.917771,"member's mark member's mark, basil, 6.25 oz",6.25,ounce,1,ounce,"[0.046231936663389206, 0.02717798389494419, -0...","[0.03072540834546089, 0.004798406735062599, 0....",NaN
6,191846,item name: goya foods sazonador total seasonin...,https://m.media-amazon.com/images/I/61dH2Ebkt0...,5.99,1.790091,"goya foods sazonador total seasoning, 30 ounce...",180.00,ounce,6,ounce,"[0.00646491814404726, -0.07859516888856888, -0...","[-0.030185913667082787, -0.014197739772498608,...",premium
7,222007,item name: vineco original series chilean sauv...,https://m.media-amazon.com/images/I/71JllaFpxM...,94.00,4.543295,vineco original series chilean sauvignon blanc...,1.00,count,1,count,"[-0.023272138088941574, -0.06071946397423744, ...","[0.016048552468419075, -0.016859684139490128, ...","crisp, delightful, zesty"
8,37614,item name: natures path cereal flk multigrain ...,https://m.media-amazon.com/images/I/21O9RftI2v...,35.74,3.576271,"natures path cereal flk multigrain org eco, 32...",192.00,fl oz,1,fl oz,"[-0.023940980434417725, 0.01450114045292139, -...","[0.04200325161218643, -0.04872272536158562, 0....",NaN
9,238044,item name: mrs. miller's seedless black raspbe...,https://m.media-amazon.com/images/I/41miQk+RkJ...,31.80,3.459466,mrs. miller's seedless black raspberry jam 9 o...,9.00,ounce,4,ounce,"[-0.10641743987798691, -0.007249758578836918, ...","[0.005712801590561867, -0.03034261055290699, 0...",pure

In [295]:
df["image_embeddings"][0]

'[0.009049994871020317, 0.00274485326372087, -0.030127644538879395, -0.02061096578836441, 0.0438159704208374, -0.02496897056698799, -0.013341407291591167, 0.01859249174594879, -0.00926909688860178, 0.01017041690647602, -0.04977896064519882, 0.003680315800011158, 0.007888146676123142, -0.0071112774312496185, 0.01168571226298809, -0.01703706942498684, 0.13816556334495544, 0.05456237867474556, -0.030592763796448708, 0.0006587631069123745, -0.13664460182189941, -0.03216315433382988, -0.0006562460330314934, -0.018323760479688644, -0.044929150491952896, 0.07610122859477997, 0.018811412155628204, 0.016470521688461304, -0.02357197180390358, -0.006560056004673243, 0.02112066000699997, 0.04596182703971863, -0.04166111350059509, 0.06595196574926376, 0.033217817544937134, -0.06342346966266632, -0.014267143793404102, 0.010462078265845776, -0.047609176486730576, 0.0894441306591034, 0.009533942677080631, -0.016992267221212387, 0.03446492180228233, -0.014851999469101429, 0.03837830200791359, 0.08044318854808807, -0.0013417055597528815, 0.0002129231725120917, 0.021155033260583878, -0.011057971976697445, 0.01963398978114128, -0.014173916541039944, 0.0406266525387764, 0.012332096695899963, 0.006164335645735264, 0.04386601224541664, -0.012793491594493389, 0.0023214868269860744, 0.07112672924995422, -0.003595843445509672, -0.007416451349854469, -0.0072309463284909725, -0.04704386368393898, 0.027784325182437897, 0.006830951664596796, 0.028855828568339348, 0.0003048846556339413, 0.09291604906320572, 0.0027148586232215166, -0.007206350099295378, -0.0473003014922142, -0.004022889770567417, -0.0004512309096753597, -0.012881837785243988, -0.02967105060815811, 0.0036036192905157804, 0.02147834189236164, -0.0020291947294026613, -0.007462749257683754, 0.002378127072006464, 0.035394586622714996, 0.009227643720805645, -0.002578006125986576, -0.06853917986154556, 0.02278219908475876, 0.04295443370938301, -0.02403859794139862, -0.029629984870553017, 0.058468230068683624, 0.05016835406422615, 0.05730418115854263, 0.030966592952609062, -0.5469426512718201, -0.0060609919019043446, 0.028984593227505684, 0.0222794059664011, -0.027054913341999054, 0.03976397588849068, -0.056131552904844284, 0.010572567582130432, 0.06153324246406555, -0.01073937676846981, -0.024838486686348915, -0.03978447616100311, -0.06648034602403641, -0.014277119189500809, -0.044879741966724396, 0.03613010048866272, 0.01842050999403, 0.0042005195282399654, 0.005773109383881092, 0.06601693481206894, -0.058665379881858826, 0.018934130668640137, 0.016893060877919197, -0.038078077137470245, 0.009964014403522015, 0.010051561519503593, -0.006467730738222599, -0.07532129436731339, 0.07211798429489136, 0.0057959724217653275, 0.01153398584574461, 0.012306549586355686, 0.0017606131732463837, -0.0025651524774730206, -0.007914715446531773, 0.013811939395964146, 0.03517674282193184, -0.08025530725717545, -0.041332144290208817, 0.024120746180415154, 0.007461934816092253, 0.08962400257587433, 0.0014573805965483189, 0.025256993249058723, 0.04263710230588913, -0.006029365584254265, -0.004849948920309544, -0.03707686811685562, 0.012438558042049408, 0.01727296970784664, -0.01907660998404026, 0.048418283462524414, -0.008199486881494522, 0.0094028040766716, -0.022273704409599304, 0.043641507625579834, 0.024548200890421867, 0.021567124873399734, -0.019674988463521004, -0.0034774162340909243, 0.04964248463511467, 0.004471260588616133, -0.03275483474135399, -0.061284467577934265, 0.04424067214131355, 0.04066331684589386, -0.04500264674425125, -0.031770821660757065, -0.04365229234099388, 0.02945910580456257, 0.06301846355199814, -0.018998876214027405, 0.007050978485494852, 0.036649975925683975, 0.021127190440893173, -0.0400032177567482, -0.019337035715579987, 0.0016961494693532586, -0.05182497575879097, -0.02340419590473175, 0.009573384188115597, 0.003690136130899191, -0.016934778541326523, 0.009789576753973961, -0.012273348867893219, 0.0062964861281216145, 0.1582868993282318, -0.003194083459675312, 0.045167066156864166, 0.040546733886003494, -0.01316189393401146, 0.017786283046007156, -0.0016735867829993367, 0.0028470992110669613, -0.00997550692409277, 0.03541383147239685, -0.020926473662257195, -0.009583844803273678, 0.01436078455299139, 0.0007426241063512862, -0.040987785905599594, -0.018658343702554703, 0.05320826917886734, 0.001145306508988142, -0.011396477930247784, -0.029204294085502625, 0.015343395061790943, -0.020371632650494576, 0.01609712652862072, -0.040076203644275665, 0.03692255914211273, 0.019084379076957703, 0.009523901157081127, 0.023886162787675858, -0.08209483325481415, 0.01551771815866232, -0.00967962946742773, 0.01886509358882904, -0.006164677441120148, 0.12572458386421204, 0.0032835702877491713, 0.08418550342321396, 0.0014450144954025745, 6.300585027929628e-06, -0.009949888102710247, -0.013782205060124397, 0.020832328125834465, 0.05216062441468239, -0.0014055714709684253, 0.07647399604320526, -0.026461955159902573, -0.014764823950827122, 0.03613137826323509, -0.024653730913996696, -0.011703248135745525, -0.035421594977378845, 0.048771604895591736, -0.0012463401071727276, -0.008940660394728184, -0.035109154880046844, 0.010862250812351704, -0.030336037278175354, 0.008659071289002895, 0.03452456369996071, -0.0023563371505588293, -0.028556158766150475, -0.029377466067671776, 0.0241090040653944, 0.013002307154238224, -0.009430120699107647, 0.0020637926645576954, -0.02257395349442959, -0.015400259755551815, -0.028227536007761955, 0.0664791688323021, 0.10037978738546371, -0.009998386725783348, 0.015351926907896996, 0.008171730674803257, -0.022017493844032288, -0.003164843888953328, -0.0031131694559007883, 0.02091214805841446, 0.09593634307384491, -0.021146206185221672, -0.012006795965135098, -0.05132623761892319, 0.02172933891415596, 0.0058848368935287, 0.020520100370049477, 0.009249246679246426, 0.04696958512067795, -0.06759562343358994, 0.05426213517785072, 0.026737574487924576, 0.00807182490825653, 0.0726017877459526, 0.0038997558876872063, -0.020937643945217133, 0.010169369168579578, -0.02077990584075451, 0.018077759072184563, 0.004450296983122826, -0.021592574194073677, -0.04074824973940849, -0.012521252036094666, -0.013972046785056591, 0.014736199751496315, -0.04574985429644585, 0.01915593072772026, -0.01995493844151497, 0.015259337611496449, 0.009586472064256668, 0.028561502695083618, 0.05185262858867645, 0.021580982953310013, -0.03252410143613815, -0.0010877412278205156, 0.05776587873697281, 0.017730074003338814, -0.05635448172688484, -0.009009859524667263, -0.05315503478050232, 0.003430176293477416, 0.08774688094854355, -0.008808312006294727, 0.007353223394602537, 0.006255166605114937, -0.04683087766170502, 0.0008017446962185204, -0.012631352990865707, -0.007673855405300856, -0.016912993043661118, -0.01815130189061165, -0.015859929844737053, -0.001944831688888371, -0.0031205504201352596, -0.05476952716708183, 0.016178825870156288, 0.01999134011566639, 0.08959633111953735, -0.01722007803618908, -0.023224178701639175, 0.05510953068733215, 0.021616367623209953, 0.06651069223880768, 0.02436772733926773, 0.006131923291832209, -0.007461105473339558, 0.11571147292852402, -0.018109029158949852, -0.035682059824466705, -0.0570937842130661, -0.019949713721871376, 0.04425835236907005, 0.00774277001619339, 0.07766303420066833, 0.002582005923613906, 0.011965443380177021, 0.012664876878261566, -0.0018032601801678538, -0.011617295444011688, 0.0026738925371319056, 0.03132273629307747, 0.03855092450976372, 0.012515370734035969, -0.0017017415957525373, 0.04428860545158386, -0.029442941769957542, -0.047170449048280716, 0.053538061678409576, -0.02953544817864895, 0.024267207831144333, -0.034508004784584045, -0.0223613940179348, 0.023029472678899765, -0.001559432246722281, 0.013794727623462677, -0.017591459676623344, -0.09672696143388748, 0.06698080152273178, 0.01534315012395382, -0.0035003034863620996, 0.0477488674223423, 0.0771375447511673, -0.0039025049190968275, 0.0128960395231843, 0.014851052314043045, -0.020391808822751045, -0.03583855181932449, 0.013087611645460129, 0.03157813102006912, -0.009812369011342525, -0.005771242082118988, -0.039796724915504456, 0.058492135256528854, 0.010058850049972534, 0.009624219499528408, -0.03226517140865326, -0.01633772812783718, -0.017044594511389732, 0.00885181687772274, 0.040610745549201965, -0.05215835943818092, 0.018253304064273834, 0.019749760627746582, -0.0624222606420517, 0.0013838361483067274, 0.00789985153824091, -0.007208750117570162, 0.060814883559942245, -0.06515383720397949, -0.02668341062963009, -0.02707558125257492, 0.03758999705314636, -0.031866468489170074, -0.019413091242313385, -0.014040515758097172, -0.07637560367584229, -0.06763732433319092, 0.014566159807145596, 0.0018759215017780662, 0.042153630405664444, 0.00011133428051834926, 0.03785594180226326, 0.004827913828194141, -0.004633964039385319, -0.019585253670811653, -0.024013692513108253, -0.001827763975597918, 0.012458302080631256, -0.048840273171663284, -0.015537630766630173, -0.006514102220535278, -0.007617837283760309, 0.008782691322267056, 0.02444581128656864, -0.08387117087841034, -0.05951971188187599, -0.031043175607919693, 0.0633687824010849, 0.07634028792381287, -0.0655369982123375, 0.04030422493815422, 0.0321747325360775, 0.006676067598164082, 0.03004561737179756, -0.039634913206100464, 0.02940131537616253, 0.04484523832798004, 0.027690844610333443, 0.06472502648830414, -0.011453426443040371, -0.019245654344558716, 0.021138686686754227, -0.007994243875145912, -0.12748241424560547, 0.01602885127067566, -0.004318325314670801, 0.04177815094590187, 0.14382871985435486, -0.03180604800581932, -0.009624983184039593, -0.004307655617594719, -0.0010795685229822993, -0.009000812657177448, 0.011630519293248653, -0.0045122746378183365, 0.004401573445647955, -0.005314397159963846, 0.04846665635704994, 0.02988128550350666, 0.00010168794688070193, 0.00637282058596611, -0.030033277347683907, -0.02432919852435589, 0.0015478964196518064, -0.04577043280005455, 0.03673132136464119, -0.005203223321586847, -0.021395836025476456, -0.010620733723044395, -0.06801322102546692, 0.02596299722790718, -0.0203146580606699, -0.01789969950914383, 0.04108935222029686, 0.01290958747267723, -0.01385150570422411, -0.06397227942943573, -0.02415919117629528, -0.04727654531598091, 0.008647428825497627, 0.05393195524811745, 0.00876647885888815, -0.015887202695012093, -0.03329489007592201, 0.013314614072442055, 0.03898732736706734, -0.03474341705441475, 0.00652778847143054, -0.05887483060359955, -0.004332782234996557, -0.05363928899168968, -0.012289420701563358, 0.005105690564960241, -0.012464948929846287, -0.012246882542967796, -0.06791426241397858, -0.05489908531308174, 0.01225333008915186, -0.005543735809624195, -0.011660981923341751, -0.055037032812833786, 0.007509719580411911, 0.04118289798498154, -0.0024771823082119226, -0.04389667883515358, 0.07437130808830261, -0.011294892057776451, -0.008005352690815926, -0.042912326753139496, 0.014755655080080032, -0.009042664431035519, -0.02835916168987751, 0.005731670651584864, -0.019917430356144905, -0.002091140951961279, -0.0095939040184021, 0.02509123831987381, -0.0018456003163009882, 0.03867942467331886, -0.024881424382328987, 0.019402340054512024, 0.02429165691137314, 0.014279006980359554, 0.007802673149853945, 0.04736911132931709, 0.00822100043296814, -0.036976996809244156]'

In [296]:
df.isnull().sum()

sample_id               0
catalog_content         0
image_link              0
price                   0
price_log               0
item_name               7
value                 940
unit                    1
pack                    0
unit_clean              1
text_embeddings         0
image_embeddings        0
extra_attributes    30835
dtype: int64

--------

In [297]:
# Fill missing values in extra_attributes with "none"
df['extra_attributes'] = df['extra_attributes'].fillna("none")

# Optional: also replace empty strings just in case
df['extra_attributes'] = df['extra_attributes'].replace("", "none")

# Check again
print(df['extra_attributes'].isna().sum())

0

In [298]:
df.isnull().sum()

sample_id             0
catalog_content       0
image_link            0
price                 0
price_log             0
item_name             7
value               940
unit                  1
pack                  0
unit_clean            1
text_embeddings       0
image_embeddings      0
extra_attributes      0
dtype: int64

In [299]:
df.loc[df["sample_id"] == 186165, ["value", "unit"]] = [4.25, "oz"]

In [300]:
df.isnull().sum()

sample_id             0
catalog_content       0
image_link            0
price                 0
price_log             0
item_name             7
value               939
unit                  1
pack                  0
unit_clean            1
text_embeddings       0
image_embeddings      0
extra_attributes      0
dtype: int64

hehe

In [301]:
# import pandas as pd
# import numpy as np
# from tqdm import tqdm
# from concurrent.futures import ThreadPoolExecutor
# from PIL import Image
# import requests
# import torch

# # ======================================
# # Configuration
# # ======================================
# MODEL_ID = "Qwen/Qwen2-VL-2B-Instruct"
# device = "cuda" if torch.cuda.is_available() else "cpu"
# BATCH_SIZE = 1  # safe default for small GPUs
# IMAGE_SIZE = (224, 224)  # reduce VRAM usage
# PROMPT_UV = (
#     "Look at this product image carefully. "
#     "What is the product's quantity or weight (the number) and the unit (like oz, pound, count, fl oz, etc.)? "
#     "if oz, pound, count, fl oz, doesnt suit then return other "
#     "Return only two values separated by a comma, like: '200, ml'"
# )

# # ======================================
# # Load dataset and mark missing values
# # ======================================
# # df = pd.read_csv("train_final_dataset_pitstop7486_s2.csv")  # uncomment this

# missing_tokens = ["none", "None", "null", "Null", "NULL", "nan", "NaN", "missing", "", " ", "-", "--"]
# df = df.replace(missing_tokens, np.nan)

# missing_uv_df = df[df['unit'].isnull() | df['value'].isnull()].copy()
# print(f"🧮 Found {len(missing_uv_df)} rows with missing unit/value.")

# missing_uv_df.to_csv("missing_unit_value_rows.csv", index=False)

In [302]:
# ! pip install accelerate

In [303]:
# from transformers import Qwen2VLForConditionalGeneration, AutoProcessor
# import torch

# processor = AutoProcessor.from_pretrained(MODEL_ID, trust_remote_code=True)

# model = Qwen2VLForConditionalGeneration.from_pretrained(
#     MODEL_ID,
#     torch_dtype=torch.float16
# )
# model.eval()

# # Manually send to GPU (or CPU if CUDA not available)
# device = "cuda" if torch.cuda.is_available() else "cpu"
# model.to(device)

# print("✅ Qwen2-VL loaded on", device)

In [304]:
# # Helper: Parallel image loader with resizing
# def fetch_image(url):
#     try:
#         resp = requests.get(url, stream=True, timeout=8)
#         resp.raise_for_status()
#         img = Image.open(resp.raw).convert("RGB")
#         return img.resize(IMAGE_SIZE)
#     except Exception:
#         return None

# # Batched extraction
# def extract_unit_value_batched(df, batch_size=BATCH_SIZE):
#     predicted_values, predicted_units = [], []
#     n = len(df)

#     for i in tqdm(range(0, n, batch_size), desc="⚡ Qwen Unit/Value Extraction"):
#         batch = df.iloc[i:i+batch_size]
#         image_urls = batch["image_link"].tolist()

#         # Parallel image download
#         with ThreadPoolExecutor(max_workers=batch_size) as ex:
#             images = list(ex.map(fetch_image, image_urls))

#         # Build messages batch
#         messages_batch = []
#         for img in images:
#             messages_batch.append([
#                 {
#                     "role": "user",
#                     "content": [
#                         {"type": "image", "image": img},
#                         {"type": "text", "text": PROMPT_UV},
#                     ],
#                 }
#             ])

#         # Process all prompts
#         texts, imgs_list = [], []
#         for m in messages_batch:
#             text = processor.apply_chat_template(m, tokenize=False, add_generation_prompt=True)
#             texts.append(text)
#             imgs = [c["image"] for msg in m for c in msg["content"] if c["type"] == "image"]
#             imgs_list.append(imgs)

#         # Prepare batched inputs
#         inputs = processor(
#             text=texts,
#             images=imgs_list,
#             padding=True,
#             return_tensors="pt"
#         ).to(device)

#         # Batched generation
#         with torch.no_grad():
#             generated_ids = model.generate(**inputs, max_new_tokens=50)

#         # Decode outputs
#         trimmed = [out[len(in_):] for in_, out in zip(inputs.input_ids, generated_ids)]
#         results = processor.batch_decode(trimmed, skip_special_tokens=True)

#         for r in results:
#             try:
#                 value, unit = [x.strip() for x in r.split(",")]
#             except Exception:
#                 value, unit = None, None
#             predicted_values.append(value)
#             predicted_units.append(unit)

#     df.loc[:, "predicted_value"] = predicted_values
#     df.loc[:, "predicted_unit"] = predicted_units
#     return df

# # Run extraction
# missing_uv_df = extract_unit_value_batched(missing_uv_df, batch_size=BATCH_SIZE)
# missing_uv_df.to_csv("missing_unit_value_predictions_qwen.csv", index=False)
# print("💾 Saved predictions for missing rows.")

# # Merge predictions back
# df.loc[missing_uv_df.index, "value"] = missing_uv_df["predicted_value"]
# df.loc[missing_uv_df.index, "unit"] = missing_uv_df["predicted_unit"]

# df.to_csv("train_final_dataset_with_qwen_filled.csv", index=False)
# print("✅ Missing `unit` and `value` filled and saved!")

# # Optional: inspect filled rows
# filled_rows = df.loc[missing_uv_df.index, ["item_name", "image_link", "value", "unit"]]
# print(filled_rows.head())

-------- heheheee

In [305]:
# row = df.loc[df['unit'] == 'none']
# print(row)

In [306]:
df_withoutcatalog = df.drop('catalog_content', axis=1)  # axis=1 means columns

In [307]:
df_withoutcatalog.head()

,sample_id,image_link,price,price_log,item_name,value,unit,pack,unit_clean,text_embeddings,image_embeddings,extra_attributes
0,33127,https://m.media-amazon.com/images/I/51mo8htwTH...,4.89,1.587192,"la victoria green taco sauce mild, 12 ounce (p...",72.00,fl oz,6,fl oz,"[0.036331795156002045, -0.052913691848516464, ...","[0.009049994871020317, 0.00274485326372087, -0...",none
1,198967,https://m.media-amazon.com/images/I/71YtriIHAA...,13.12,2.574138,"salerno cookies, the original butter cookies, ...",32.00,ounce,4,ounce,"[-0.01868608593940735, -0.013683686032891273, ...","[0.014290607534348965, -0.04910419136285782, 0...",classic
2,261251,https://m.media-amazon.com/images/I/51+PFEe-w-...,1.97,0.678034,"bear creek hearty soup bowl, creamy chicken wi...",11.40,ounce,6,ounce,"[0.07000485807657242, -0.06418927758932114, -0...","[-0.010892418213188648, -0.038370147347450256,...",creamy
3,55858,https://m.media-amazon.com/images/I/41mu0HAToD...,30.34,3.412467,judee’s blue cheese powder 11.25 oz - gluten-f...,11.25,ounce,1,ounce,"[-0.04193189740180969, -0.02518327534198761, 0...","[0.058143433183431625, -0.004104044754058123, ...","gluten-free, nut-free"
4,292686,https://m.media-amazon.com/images/I/41sA037+Qv...,66.49,4.197052,"kedem sherry cooking wine, 12.7 ounce - 12 per...",12.00,count,1,count,"[0.021312430500984192, 0.0017853323370218277, ...","[-0.035538848489522934, 0.009405052289366722, ...",none

In [308]:
df_withoutimglnk = df_withoutcatalog.drop('image_link', axis=1)  # axis=1 means columns

In [309]:
df_withoutimglnk.head()

,sample_id,price,price_log,item_name,value,unit,pack,unit_clean,text_embeddings,image_embeddings,extra_attributes
0,33127,4.89,1.587192,"la victoria green taco sauce mild, 12 ounce (p...",72.00,fl oz,6,fl oz,"[0.036331795156002045, -0.052913691848516464, ...","[0.009049994871020317, 0.00274485326372087, -0...",none
1,198967,13.12,2.574138,"salerno cookies, the original butter cookies, ...",32.00,ounce,4,ounce,"[-0.01868608593940735, -0.013683686032891273, ...","[0.014290607534348965, -0.04910419136285782, 0...",classic
2,261251,1.97,0.678034,"bear creek hearty soup bowl, creamy chicken wi...",11.40,ounce,6,ounce,"[0.07000485807657242, -0.06418927758932114, -0...","[-0.010892418213188648, -0.038370147347450256,...",creamy
3,55858,30.34,3.412467,judee’s blue cheese powder 11.25 oz - gluten-f...,11.25,ounce,1,ounce,"[-0.04193189740180969, -0.02518327534198761, 0...","[0.058143433183431625, -0.004104044754058123, ...","gluten-free, nut-free"
4,292686,66.49,4.197052,"kedem sherry cooking wine, 12.7 ounce - 12 per...",12.00,count,1,count,"[0.021312430500984192, 0.0017853323370218277, ...","[-0.035538848489522934, 0.009405052289366722, ...",none

In [310]:
df_withoutprice = df_withoutimglnk.drop('price', axis=1)  # axis=1 means columns

In [311]:
df_withoutprice.head()

,sample_id,price_log,item_name,value,unit,pack,unit_clean,text_embeddings,image_embeddings,extra_attributes
0,33127,1.587192,"la victoria green taco sauce mild, 12 ounce (p...",72.00,fl oz,6,fl oz,"[0.036331795156002045, -0.052913691848516464, ...","[0.009049994871020317, 0.00274485326372087, -0...",none
1,198967,2.574138,"salerno cookies, the original butter cookies, ...",32.00,ounce,4,ounce,"[-0.01868608593940735, -0.013683686032891273, ...","[0.014290607534348965, -0.04910419136285782, 0...",classic
2,261251,0.678034,"bear creek hearty soup bowl, creamy chicken wi...",11.40,ounce,6,ounce,"[0.07000485807657242, -0.06418927758932114, -0...","[-0.010892418213188648, -0.038370147347450256,...",creamy
3,55858,3.412467,judee’s blue cheese powder 11.25 oz - gluten-f...,11.25,ounce,1,ounce,"[-0.04193189740180969, -0.02518327534198761, 0...","[0.058143433183431625, -0.004104044754058123, ...","gluten-free, nut-free"
4,292686,4.197052,"kedem sherry cooking wine, 12.7 ounce - 12 per...",12.00,count,1,count,"[0.021312430500984192, 0.0017853323370218277, ...","[-0.035538848489522934, 0.009405052289366722, ...",none

In [312]:
data=df_withoutprice

In [313]:
data.head()

,sample_id,price_log,item_name,value,unit,pack,unit_clean,text_embeddings,image_embeddings,extra_attributes
0,33127,1.587192,"la victoria green taco sauce mild, 12 ounce (p...",72.00,fl oz,6,fl oz,"[0.036331795156002045, -0.052913691848516464, ...","[0.009049994871020317, 0.00274485326372087, -0...",none
1,198967,2.574138,"salerno cookies, the original butter cookies, ...",32.00,ounce,4,ounce,"[-0.01868608593940735, -0.013683686032891273, ...","[0.014290607534348965, -0.04910419136285782, 0...",classic
2,261251,0.678034,"bear creek hearty soup bowl, creamy chicken wi...",11.40,ounce,6,ounce,"[0.07000485807657242, -0.06418927758932114, -0...","[-0.010892418213188648, -0.038370147347450256,...",creamy
3,55858,3.412467,judee’s blue cheese powder 11.25 oz - gluten-f...,11.25,ounce,1,ounce,"[-0.04193189740180969, -0.02518327534198761, 0...","[0.058143433183431625, -0.004104044754058123, ...","gluten-free, nut-free"
4,292686,4.197052,"kedem sherry cooking wine, 12.7 ounce - 12 per...",12.00,count,1,count,"[0.021312430500984192, 0.0017853323370218277, ...","[-0.035538848489522934, 0.009405052289366722, ...",none

In [314]:
import numpy as np

In [315]:
from sentence_transformers import SentenceTransformer

print("\n🔹 Generating text embeddings...")

# Load model (CPU or GPU)
device = "cuda"  # or "cpu"
text_model = SentenceTransformer("all-MiniLM-L12-v2", device=device)

# Convert item_name column to list of strings
brand_texts = data["item_name"].astype(str).tolist()

# Generate embeddings
brand_text_embeddings = text_model.encode(
    brand_texts,
    batch_size=64,
    show_progress_bar=True
)
np.save("train_brand_embeddings_s2.npy", brand_text_embeddings)
# Save embeddings into the DataFrame
data["item_name_embeddings"] = list(brand_text_embeddings)

# Optional: Check the first few rows
print(data.head())

🔹 Generating text embeddings...

Batches: 100%|██████████| 1172/1172 [00:41<00:00, 27.96it/s]

   sample_id  price_log                                          item_name  \
0      33127   1.587192  la victoria green taco sauce mild, 12 ounce (p...
1     198967   2.574138  salerno cookies, the original butter cookies, ...
2     261251   0.678034  bear creek hearty soup bowl, creamy chicken wi...
3      55858   3.412467  judee’s blue cheese powder 11.25 oz - gluten-f...
4     292686   4.197052  kedem sherry cooking wine, 12.7 ounce - 12 per...

   value   unit  pack unit_clean  \
0  72.00  fl oz     6      fl oz
1  32.00  ounce     4      ounce
2  11.40  ounce     6      ounce
3  11.25  ounce     1      ounce
4  12.00  count     1      count

                                     text_embeddings  \
0  [0.036331795156002045, -0.052913691848516464, ...
1  [-0.01868608593940735, -0.013683686032891273, ...
2  [0.07000485807657242, -0.06418927758932114, -0...
3  [-0.04193189740180969, -0.02518327534198761, 0...
4  [0.021312430500984192, 0.0017853323370218277, ...

                                    image_embeddings       extra_attributes  \
0  [0.009049994871020317, 0.00274485326372087, -0...                   none
1  [0.014290607534348965, -0.04910419136285782, 0...                classic
2  [-0.010892418213188648, -0.038370147347450256,...                 creamy
3  [0.058143433183431625, -0.004104044754058123, ...  gluten-free, nut-free
4  [-0.035538848489522934, 0.009405052289366722, ...                   none

                                item_name_embeddings
0  [-0.006221588, -0.046351764, -0.026960287, 0.0...
1  [-0.018365428, -0.007958315, -0.034231354, 0.0...
2  [0.068740316, -0.07668627, -0.0019331452, 0.05...
3  [-0.054631617, -0.019430207, 0.017474938, -0.1...
4  [0.015381876, -0.00023277814, -0.08660597, 0.0...

In [316]:
data.head()

,sample_id,price_log,item_name,value,unit,pack,unit_clean,text_embeddings,image_embeddings,extra_attributes,item_name_embeddings
0,33127,1.587192,"la victoria green taco sauce mild, 12 ounce (p...",72.00,fl oz,6,fl oz,"[0.036331795156002045, -0.052913691848516464, ...","[0.009049994871020317, 0.00274485326372087, -0...",none,"[-0.006221588, -0.046351764, -0.026960287, 0.0..."
1,198967,2.574138,"salerno cookies, the original butter cookies, ...",32.00,ounce,4,ounce,"[-0.01868608593940735, -0.013683686032891273, ...","[0.014290607534348965, -0.04910419136285782, 0...",classic,"[-0.018365428, -0.007958315, -0.034231354, 0.0..."
2,261251,0.678034,"bear creek hearty soup bowl, creamy chicken wi...",11.40,ounce,6,ounce,"[0.07000485807657242, -0.06418927758932114, -0...","[-0.010892418213188648, -0.038370147347450256,...",creamy,"[0.068740316, -0.07668627, -0.0019331452, 0.05..."
3,55858,3.412467,judee’s blue cheese powder 11.25 oz - gluten-f...,11.25,ounce,1,ounce,"[-0.04193189740180969, -0.02518327534198761, 0...","[0.058143433183431625, -0.004104044754058123, ...","gluten-free, nut-free","[-0.054631617, -0.019430207, 0.017474938, -0.1..."
4,292686,4.197052,"kedem sherry cooking wine, 12.7 ounce - 12 per...",12.00,count,1,count,"[0.021312430500984192, 0.0017853323370218277, ...","[-0.035538848489522934, 0.009405052289366722, ...",none,"[0.015381876, -0.00023277814, -0.08660597, 0.0..."

In [317]:
data2 = data.drop('item_name', axis=1)  # axis=1 means columns

In [318]:
data2.head()

,sample_id,price_log,value,unit,pack,unit_clean,text_embeddings,image_embeddings,extra_attributes,item_name_embeddings
0,33127,1.587192,72.00,fl oz,6,fl oz,"[0.036331795156002045, -0.052913691848516464, ...","[0.009049994871020317, 0.00274485326372087, -0...",none,"[-0.006221588, -0.046351764, -0.026960287, 0.0..."
1,198967,2.574138,32.00,ounce,4,ounce,"[-0.01868608593940735, -0.013683686032891273, ...","[0.014290607534348965, -0.04910419136285782, 0...",classic,"[-0.018365428, -0.007958315, -0.034231354, 0.0..."
2,261251,0.678034,11.40,ounce,6,ounce,"[0.07000485807657242, -0.06418927758932114, -0...","[-0.010892418213188648, -0.038370147347450256,...",creamy,"[0.068740316, -0.07668627, -0.0019331452, 0.05..."
3,55858,3.412467,11.25,ounce,1,ounce,"[-0.04193189740180969, -0.02518327534198761, 0...","[0.058143433183431625, -0.004104044754058123, ...","gluten-free, nut-free","[-0.054631617, -0.019430207, 0.017474938, -0.1..."
4,292686,4.197052,12.00,count,1,count,"[0.021312430500984192, 0.0017853323370218277, ...","[-0.035538848489522934, 0.009405052289366722, ...",none,"[0.015381876, -0.00023277814, -0.08660597, 0.0..."

In [319]:
data2["unit"].unique()

array(['fl oz', 'ounce', 'count', 'oz', 'none', 'fluid ounce', 'ounces',
       'pound', 'gram', 'grams', 'lb', 'each', 'liters', 'gramm', 'ct',
       'millilitre', 'jar', 'fl. oz', 'bottle', 'can', 'tea bags',
       '20 oz.', 'each / pack: 1', '24', 'pack', 'piece', 'fluid ounces',
       'gr', 'milliliter', 'mililitro', '2.5 gal.', 'pounds', 'kg', 'bag',
       'in', 'fl. oz.', 'k-cups', 'sq ft', '-', 'ml', 'packs', 'box', '8',
       'fl ounce', 'pouch', 'bucket', 'per box', 'per package',
       '1 pk. color(s): -black. product type: -permanent. pack quantity: -1. tip type: -chisel. dimensions: overall product weight: -0.06 lbs.',
       'fluid ounce(s)',
       'comes as a single 0.1 oz stick for on-the-go use', 'units',
       'case', 'box/12', '1', 'product_weight', 'per carton', 'foot',
       'grams(gm)',
       'cm/inch) ??size:s---us:4---bust:96cm/37.80---length:66cm/25.98---shoulder to sleeve:63cm/24.80 ??size:m---us:6---bust:100cm/39.37---length:67cm/26.38---shoulder to sleeve:64cm/25.20 ??size:l---us:8---bust:104cm/40.94---length:68cm/26.77---shoulder to sleeve:65cm/25.59 ??size:xl---us:10---bust:108cm/42.52---length:69cm/27.17---shoulder to sleeve:66cm/25.98 ??size:xxl---us:12---bust:112cm/44.09---length:70cm/27.56---shoulder to sleeve:67cm/26.38 ??size:xxxl---us:14---bust:116cm/45.67---length:70cm/27.56---shoulder to sleeve:68cm/26.77',
       'unità', 'paper cupcake liners', 'capsule', 'bottles', nan, '---',
       'fl.oz', 'ziplock bags', 'ltr', 'carton', '7,2 oz'], dtype=object)

In [320]:
# Count occurrences
unit_counts = data2["unit"].value_counts()

# Convert to DataFrame
unit_counts_df = unit_counts.reset_index()
unit_counts_df.columns = ['unit', 'count']

# Show all rows
pd.set_option('display.max_rows', None)
print(unit_counts_df)

                                                 unit  count
0                                               ounce  42942
1                                               count  18209
2                                               fl oz  11257
3                                                  oz   1065
4                                                none    939
5                                               pound    202
6                                                  ct     49
7                                                gram     39
8                                                  lb     34
9                                         fluid ounce     33
10                                             fl. oz     21
11                                               each     21
12                                             ounces     20
13                                       fluid ounces     14
14                                              packs     12
15                                             bottle      9
16                                               pack      9
17                                         millilitre      9
18                                             liters      7
19                                                bag      6
20                                                can      6
21                                                 kg      6
22                                     fluid ounce(s)      6
23                                              gramm      6
24                                     each / pack: 1      5
25                                             pounds      4
26                                                jar      4
27                                              piece      3
28                                             k-cups      3
29                                              grams      3
30                                         milliliter      3
31                                         per carton      3
32                                                 gr      2
33                                            per box      2
34                                                box      2
35                                           2.5 gal.      2
36                                              sq ft      2
37                                           tea bags      2
38                                               foot      2
39                                     product_weight      2
40                               paper cupcake liners      2
41                                                 ml      2
42                                                  1      2
43                                              pouch      2
44                                             20 oz.      1
45                                          mililitro      1
46                                                 in      1
47                                            fl. oz.      1
48                                                 24      1
49                                        per package      1
50                                             bucket      1
51                                           fl ounce      1
52                                                  -      1
53                                                  8      1
54                                             box/12      1
55                                               case      1
56                                              units      1
57   comes as a single 0.1 oz stick for on-the-go use      1
58  1 pk. color(s): -black. product type: -permane...      1
59                                          grams(gm)      1
60  cm/inch) ??size:s---us:4---bust:96cm/37.80---l...      1
61                                              unità      1
62                                            capsule      1
63                                            bottles      1
64                                                ---      1
65                                              fl.oz      1
66                                       ziplock bags      1
67                                                ltr      1
68                                             carton      1
69                                             7,2 oz      1

In [321]:
# Filter rows where unit is "count"
count_rows = data2[data2["unit"] == "count"]

# Show the first few rows
count_rows.head()

,sample_id,price_log,value,unit,pack,unit_clean,text_embeddings,image_embeddings,extra_attributes,item_name_embeddings
4,292686,4.197052,12.0,count,1,count,"[0.021312430500984192, 0.0017853323370218277, ...","[-0.035538848489522934, 0.009405052289366722, ...",none,"[0.015381876, -0.00023277814, -0.08660597, 0.0..."
7,222007,4.543295,1.0,count,1,count,"[-0.023272138088941574, -0.06071946397423744, ...","[0.016048552468419075, -0.016859684139490128, ...","crisp, delightful, zesty","[-0.08568593, -0.056396045, -0.06584765, -0.04..."
12,21740,1.943049,4.0,count,1,count,"[-0.018269607797265053, 0.025456957519054413, ...","[-0.002668810775503516, 0.005417943000793457, ...","non-gmo, dairy-free, vegan","[-0.029120293, 0.02080524, 0.056205213, 0.0539..."
19,260842,3.931630,90.0,count,1,count,"[-0.06530505418777466, -0.05679032951593399, -...","[-0.04064779356122017, 0.022225581109523773, 0...","premium, smooth, non-gmo, vegan, rich","[-0.052941833, -0.06607809, -0.0041437736, 0.0..."
21,201749,3.468544,20.0,count,1,count,"[-0.061352428048849106, -0.014882011339068413,...","[-0.02526291087269783, -0.004183936398476362, ...","vegan, non-gmo, soy-free, dairy-free, stevia-free","[-0.07574127, -0.009647501, 0.042097967, 0.036..."

In [322]:
import pandas as pd

# Example: your dataset
# data2 = pd.read_csv("your_dataset.csv")

# Conversion constants
ML_TO_FLOZ = 0.033814   # 1 mL = 0.033814 fl oz
L_TO_FLOZ = 33.814      # 1 liter = 33.814 fl oz
GRAM_TO_LB = 0.00220462 # 1 gram = 0.00220462 pound
KG_TO_LB = 2.20462      # 1 kg = 2.20462 pound

def normalize_units(row):
    unit = str(row['unit']).lower().strip()
    value = row['value']

    # -----------------------------
    # COUNTABLE UNITS
    # -----------------------------
    if unit in ['count', 'ct', 'each', 'pack', 'packs', 'piece', 'each / pack: 1']:
        return value, 'count'

    # -----------------------------
    # WEIGHT UNITS
    # -----------------------------
    elif unit in ['oz', 'ounce', 'ounces']:
        return value, 'oz'
    elif unit in ['pound', 'lb', 'lbs', 'pounds']:
        return value, 'pound'
    elif unit in ['gram', 'grams', 'gramm', 'g']:
        return value * GRAM_TO_LB, 'pound'
    elif unit in ['kg', 'kilogram', 'kilograms']:
        return value * KG_TO_LB, 'pound'

    # -----------------------------
    # LIQUID UNITS → convert all to fl oz
    # -----------------------------
    elif unit in ['fl oz', 'fl. oz', 'fluid ounce', 'fluid ounces', 'fluid ounce(s)']:
        return value, 'fl oz'
    elif unit in ['ml', 'milliliter', 'milliliters', 'millilitre', 'millilitres', 'mililitro']:
        return value * ML_TO_FLOZ, 'fl oz'
    elif unit in ['l', 'ltr', 'liter', 'liters']:
        return value * L_TO_FLOZ, 'fl oz'

    # -----------------------------
    # DEFAULT: leave as-is (optional)
    # -----------------------------
    else:
        return value, unit

# Apply the function
data2[['value_normalized', 'unit_normalized']] = data2.apply(
    normalize_units, axis=1, result_type='expand'
)

# Optional: check results
print(data2[['unit', 'value', 'unit_normalized', 'value_normalized']].head(20))

     unit   value unit_normalized  value_normalized
0   fl oz   72.00           fl oz             72.00
1   ounce   32.00              oz             32.00
2   ounce   11.40              oz             11.40
3   ounce   11.25              oz             11.25
4   count   12.00           count             12.00
5   ounce    6.25              oz              6.25
6   ounce  180.00              oz            180.00
7   count    1.00           count              1.00
8   fl oz  192.00           fl oz            192.00
9   ounce    9.00              oz              9.00
10  ounce   12.00              oz             12.00
11  ounce  160.00              oz            160.00
12  count    4.00           count              4.00
13  fl oz  192.00           fl oz            192.00
14  fl oz  336.00           fl oz            336.00
15  fl oz  102.00           fl oz            102.00
16  ounce   10.00              oz             10.00
17  ounce  192.00              oz            192.00
18  ounce  176.37              oz            176.37
19  count   90.00           count             90.00

In [323]:
# Count occurrences
norm_unit_counts = data2["unit_normalized"].value_counts()

# Convert to DataFrame
norm_unit_counts_df = norm_unit_counts.reset_index()
norm_unit_counts_df.columns = ['unit', 'count']

# Show all rows
pd.set_option('display.max_rows', None)
print(norm_unit_counts_df)

                                                 unit  count
0                                                  oz  44027
1                                               count  18308
2                                               fl oz  11354
3                                                none    939
4                                               pound    294
5                                              bottle      9
6                                                 can      6
7                                                 bag      6
8                                                 jar      4
9                                          per carton      3
10                                             k-cups      3
11                                           2.5 gal.      2
12                                              pouch      2
13                                                 gr      2
14                                           tea bags      2
15                                               foot      2
16                               paper cupcake liners      2
17                                                  1      2
18                                              sq ft      2
19                                            per box      2
20                                     product_weight      2
21                                                box      2
22                                             20 oz.      1
23                                                 in      1
24                                                 24      1
25                                        per package      1
26                                             bucket      1
27                                           fl ounce      1
28                                                  -      1
29                                                  8      1
30                                            fl. oz.      1
31                                             box/12      1
32                                               case      1
33                                              units      1
34   comes as a single 0.1 oz stick for on-the-go use      1
35  1 pk. color(s): -black. product type: -permane...      1
36                                          grams(gm)      1
37  cm/inch) ??size:s---us:4---bust:96cm/37.80---l...      1
38                                              unità      1
39                                            capsule      1
40                                            bottles      1
41                                                nan      1
42                                                ---      1
43                                              fl.oz      1
44                                       ziplock bags      1
45                                             carton      1
46                                             7,2 oz      1

In [324]:
data2.head()

,sample_id,price_log,value,unit,pack,unit_clean,text_embeddings,image_embeddings,extra_attributes,item_name_embeddings,value_normalized,unit_normalized
0,33127,1.587192,72.00,fl oz,6,fl oz,"[0.036331795156002045, -0.052913691848516464, ...","[0.009049994871020317, 0.00274485326372087, -0...",none,"[-0.006221588, -0.046351764, -0.026960287, 0.0...",72.00,fl oz
1,198967,2.574138,32.00,ounce,4,ounce,"[-0.01868608593940735, -0.013683686032891273, ...","[0.014290607534348965, -0.04910419136285782, 0...",classic,"[-0.018365428, -0.007958315, -0.034231354, 0.0...",32.00,oz
2,261251,0.678034,11.40,ounce,6,ounce,"[0.07000485807657242, -0.06418927758932114, -0...","[-0.010892418213188648, -0.038370147347450256,...",creamy,"[0.068740316, -0.07668627, -0.0019331452, 0.05...",11.40,oz
3,55858,3.412467,11.25,ounce,1,ounce,"[-0.04193189740180969, -0.02518327534198761, 0...","[0.058143433183431625, -0.004104044754058123, ...","gluten-free, nut-free","[-0.054631617, -0.019430207, 0.017474938, -0.1...",11.25,oz
4,292686,4.197052,12.00,count,1,count,"[0.021312430500984192, 0.0017853323370218277, ...","[-0.035538848489522934, 0.009405052289366722, ...",none,"[0.015381876, -0.00023277814, -0.08660597, 0.0...",12.00,count

In [325]:
final_data=data2.drop(columns=['unit', 'unit_clean', 'value'])

In [326]:
final_data.head()

,sample_id,price_log,pack,text_embeddings,image_embeddings,extra_attributes,item_name_embeddings,value_normalized,unit_normalized
0,33127,1.587192,6,"[0.036331795156002045, -0.052913691848516464, ...","[0.009049994871020317, 0.00274485326372087, -0...",none,"[-0.006221588, -0.046351764, -0.026960287, 0.0...",72.00,fl oz
1,198967,2.574138,4,"[-0.01868608593940735, -0.013683686032891273, ...","[0.014290607534348965, -0.04910419136285782, 0...",classic,"[-0.018365428, -0.007958315, -0.034231354, 0.0...",32.00,oz
2,261251,0.678034,6,"[0.07000485807657242, -0.06418927758932114, -0...","[-0.010892418213188648, -0.038370147347450256,...",creamy,"[0.068740316, -0.07668627, -0.0019331452, 0.05...",11.40,oz
3,55858,3.412467,1,"[-0.04193189740180969, -0.02518327534198761, 0...","[0.058143433183431625, -0.004104044754058123, ...","gluten-free, nut-free","[-0.054631617, -0.019430207, 0.017474938, -0.1...",11.25,oz
4,292686,4.197052,1,"[0.021312430500984192, 0.0017853323370218277, ...","[-0.035538848489522934, 0.009405052289366722, ...",none,"[0.015381876, -0.00023277814, -0.08660597, 0.0...",12.00,count

In [327]:
# Define liquid and count units
liquid_units = ["fl.oz", "fl oz", "oz.","fl ounce","fl. oz.","20 oz."]  # normalize to "fl oz"
count_units = [
    "bottle", "can", "bag", "jar", "per carton", "k-cups", 
    "pouch", "tea bags", "paper cupcake liners", "1", "box", 
    "ziplock bags", "carton" , "bottles","bucket","units","8","24","per package","comes as a single 0.1 oz stick for on-the-go use"
]

# Function to normalize units
def normalize_unit(x):
    if pd.isna(x):
        return None
    x = str(x).lower().strip()
    
    # Normalize specific liquid units
    if x in liquid_units:
        return "fl oz"
    
    # Map other units to 'count'
    elif x in count_units:
        return "count"
    
    # Otherwise keep original
    else:
        return x

# Apply normalization
final_data['unit_normalized'] = final_data['unit_normalized'].apply(normalize_unit)

# Optional: check results
print(final_data[['unit_normalized']].head(20))

   unit_normalized
0            fl oz
1               oz
2               oz
3               oz
4            count
5               oz
6               oz
7            count
8            fl oz
9               oz
10              oz
11              oz
12           count
13           fl oz
14           fl oz
15           fl oz
16              oz
17              oz
18              oz
19           count

In [328]:
# Count occurrences
norm_unit_counts =final_data["unit_normalized"].value_counts()

# Convert to DataFrame
norm_unit_counts_df = norm_unit_counts.reset_index()
norm_unit_counts_df.columns = ['unit', 'count']

# Show all rows
pd.set_option('display.max_rows', None)
print(norm_unit_counts_df)

                                                 unit  count
0                                                  oz  44027
1                                               count  18358
2                                               fl oz  11358
3                                                none    939
4                                               pound    294
5                                                  gr      2
6                                            2.5 gal.      2
7                                               sq ft      2
8                                             per box      2
9                                      product_weight      2
10                                               foot      2
11                                                  -      1
12  1 pk. color(s): -black. product type: -permane...      1
13                                               case      1
14                                                 in      1
15                                             box/12      1
16                                          grams(gm)      1
17  cm/inch) ??size:s---us:4---bust:96cm/37.80---l...      1
18                                              unità      1
19                                            capsule      1
20                                                nan      1
21                                                ---      1
22                                             7,2 oz      1

In [329]:
df.isnull().sum()

sample_id             0
catalog_content       0
image_link            0
price                 0
price_log             0
item_name             7
value               939
unit                  1
pack                  0
unit_clean            1
text_embeddings       0
image_embeddings      0
extra_attributes      0
dtype: int64

In [330]:
import torch
import torch.nn as nn

# Map unit to index
unit_encoder = {unit: i for i, unit in enumerate(final_data['unit_normalized'].unique())}

# Create unit_idx in final_data
final_data['unit_idx'] = final_data['unit_normalized'].map(unit_encoder)

# PyTorch embedding layer
num_units = len(unit_encoder)      # 3 in your case
embedding_dim = 4                  # small number since only 3 units
embedding_layer = nn.Embedding(num_units, embedding_dim)

# Convert to tensor
unit_tensor = torch.tensor(final_data['unit_idx'].values, dtype=torch.long)

# Get embeddings
unit_embedded = embedding_layer(unit_tensor)  # shape: [num_rows, embedding_dim]

In [331]:
final_data.head()

,sample_id,price_log,pack,text_embeddings,image_embeddings,extra_attributes,item_name_embeddings,value_normalized,unit_normalized,unit_idx
0,33127,1.587192,6,"[0.036331795156002045, -0.052913691848516464, ...","[0.009049994871020317, 0.00274485326372087, -0...",none,"[-0.006221588, -0.046351764, -0.026960287, 0.0...",72.00,fl oz,0
1,198967,2.574138,4,"[-0.01868608593940735, -0.013683686032891273, ...","[0.014290607534348965, -0.04910419136285782, 0...",classic,"[-0.018365428, -0.007958315, -0.034231354, 0.0...",32.00,oz,1
2,261251,0.678034,6,"[0.07000485807657242, -0.06418927758932114, -0...","[-0.010892418213188648, -0.038370147347450256,...",creamy,"[0.068740316, -0.07668627, -0.0019331452, 0.05...",11.40,oz,1
3,55858,3.412467,1,"[-0.04193189740180969, -0.02518327534198761, 0...","[0.058143433183431625, -0.004104044754058123, ...","gluten-free, nut-free","[-0.054631617, -0.019430207, 0.017474938, -0.1...",11.25,oz,1
4,292686,4.197052,1,"[0.021312430500984192, 0.0017853323370218277, ...","[-0.035538848489522934, 0.009405052289366722, ...",none,"[0.015381876, -0.00023277814, -0.08660597, 0.0...",12.00,count,2

In [332]:
final_data.rename(columns={'item_name_embeddings': 'brand_product_embedding'}, inplace=True)

In [333]:
final_data.head()

,sample_id,price_log,pack,text_embeddings,image_embeddings,extra_attributes,brand_product_embedding,value_normalized,unit_normalized,unit_idx
0,33127,1.587192,6,"[0.036331795156002045, -0.052913691848516464, ...","[0.009049994871020317, 0.00274485326372087, -0...",none,"[-0.006221588, -0.046351764, -0.026960287, 0.0...",72.00,fl oz,0
1,198967,2.574138,4,"[-0.01868608593940735, -0.013683686032891273, ...","[0.014290607534348965, -0.04910419136285782, 0...",classic,"[-0.018365428, -0.007958315, -0.034231354, 0.0...",32.00,oz,1
2,261251,0.678034,6,"[0.07000485807657242, -0.06418927758932114, -0...","[-0.010892418213188648, -0.038370147347450256,...",creamy,"[0.068740316, -0.07668627, -0.0019331452, 0.05...",11.40,oz,1
3,55858,3.412467,1,"[-0.04193189740180969, -0.02518327534198761, 0...","[0.058143433183431625, -0.004104044754058123, ...","gluten-free, nut-free","[-0.054631617, -0.019430207, 0.017474938, -0.1...",11.25,oz,1
4,292686,4.197052,1,"[0.021312430500984192, 0.0017853323370218277, ...","[-0.035538848489522934, 0.009405052289366722, ...",none,"[0.015381876, -0.00023277814, -0.08660597, 0.0...",12.00,count,2

In [334]:

# final_data.to_csv('train_final_dataset_akash.csv')

In [335]:
# Create total_value feature
final_data['total_value'] = final_data['value_normalized'] * final_data['pack']

# Optional: check first few rows
final_data.head()

,sample_id,price_log,pack,text_embeddings,image_embeddings,extra_attributes,brand_product_embedding,value_normalized,unit_normalized,unit_idx,total_value
0,33127,1.587192,6,"[0.036331795156002045, -0.052913691848516464, ...","[0.009049994871020317, 0.00274485326372087, -0...",none,"[-0.006221588, -0.046351764, -0.026960287, 0.0...",72.00,fl oz,0,432.00
1,198967,2.574138,4,"[-0.01868608593940735, -0.013683686032891273, ...","[0.014290607534348965, -0.04910419136285782, 0...",classic,"[-0.018365428, -0.007958315, -0.034231354, 0.0...",32.00,oz,1,128.00
2,261251,0.678034,6,"[0.07000485807657242, -0.06418927758932114, -0...","[-0.010892418213188648, -0.038370147347450256,...",creamy,"[0.068740316, -0.07668627, -0.0019331452, 0.05...",11.40,oz,1,68.40
3,55858,3.412467,1,"[-0.04193189740180969, -0.02518327534198761, 0...","[0.058143433183431625, -0.004104044754058123, ...","gluten-free, nut-free","[-0.054631617, -0.019430207, 0.017474938, -0.1...",11.25,oz,1,11.25
4,292686,4.197052,1,"[0.021312430500984192, 0.0017853323370218277, ...","[-0.035538848489522934, 0.009405052289366722, ...",none,"[0.015381876, -0.00023277814, -0.08660597, 0.0...",12.00,count,2,12.00

In [336]:
final_data = final_data.drop(columns=['value_normalized', 'pack'])

In [337]:
final_data.head()

,sample_id,price_log,text_embeddings,image_embeddings,extra_attributes,brand_product_embedding,unit_normalized,unit_idx,total_value
0,33127,1.587192,"[0.036331795156002045, -0.052913691848516464, ...","[0.009049994871020317, 0.00274485326372087, -0...",none,"[-0.006221588, -0.046351764, -0.026960287, 0.0...",fl oz,0,432.00
1,198967,2.574138,"[-0.01868608593940735, -0.013683686032891273, ...","[0.014290607534348965, -0.04910419136285782, 0...",classic,"[-0.018365428, -0.007958315, -0.034231354, 0.0...",oz,1,128.00
2,261251,0.678034,"[0.07000485807657242, -0.06418927758932114, -0...","[-0.010892418213188648, -0.038370147347450256,...",creamy,"[0.068740316, -0.07668627, -0.0019331452, 0.05...",oz,1,68.40
3,55858,3.412467,"[-0.04193189740180969, -0.02518327534198761, 0...","[0.058143433183431625, -0.004104044754058123, ...","gluten-free, nut-free","[-0.054631617, -0.019430207, 0.017474938, -0.1...",oz,1,11.25
4,292686,4.197052,"[0.021312430500984192, 0.0017853323370218277, ...","[-0.035538848489522934, 0.009405052289366722, ...",none,"[0.015381876, -0.00023277814, -0.08660597, 0.0...",count,2,12.00

In [338]:
from sentence_transformers import SentenceTransformer
import numpy as np

print("\n🔹 Generating embeddings for extra_attributes...")

# Load model (CPU or GPU)
device = "cuda"  # or "cpu"
text_model = SentenceTransformer("all-MiniLM-L12-v2", device=device)

# Convert extra_attributes column to list of strings
extra_texts = final_data["extra_attributes"].astype(str).tolist()

# Generate embeddings in batch
extra_text_embeddings = text_model.encode(
    extra_texts,
    batch_size=64,           # adjust based on your GPU memory
    show_progress_bar=True,
    convert_to_numpy=True     # outputs numpy array
)

# Save embeddings as a .npy file (optional)
np.save("extra_attributes_embeddings_train.npy", extra_text_embeddings)

# Add embeddings to DataFrame as list for compatibility
final_data["extra_attributes_emb"] = [emb.tolist() for emb in extra_text_embeddings]

# Optional: Check
print(final_data[["extra_attributes", "extra_attributes_emb"]].head())

🔹 Generating embeddings for extra_attributes...

Batches: 100%|██████████| 1172/1172 [00:18<00:00, 64.88it/s]

        extra_attributes                               extra_attributes_emb
0                   none  [0.0014492346672341228, -0.0001916056789923459...
1                classic  [-0.0375388078391552, 0.028431806713342667, 0....
2                 creamy  [-0.007928319275379181, -0.07840053737163544, ...
3  gluten-free, nut-free  [0.014764228835701942, 0.012520834803581238, 0...
4                   none  [0.0014492346672341228, -0.0001916056789923459...

In [339]:
final_data = final_data[[
    'sample_id',
    'text_embeddings',
    'image_embeddings',
    'brand_product_embedding',
    'total_value',
    'unit_idx',
    'extra_attributes_emb',
    'price_log'
]]

In [340]:
final_data.head()

,sample_id,text_embeddings,image_embeddings,brand_product_embedding,total_value,unit_idx,extra_attributes_emb,price_log
0,33127,"[0.036331795156002045, -0.052913691848516464, ...","[0.009049994871020317, 0.00274485326372087, -0...","[-0.006221588, -0.046351764, -0.026960287, 0.0...",432.00,0,"[0.0014492346672341228, -0.0001916056789923459...",1.587192
1,198967,"[-0.01868608593940735, -0.013683686032891273, ...","[0.014290607534348965, -0.04910419136285782, 0...","[-0.018365428, -0.007958315, -0.034231354, 0.0...",128.00,1,"[-0.0375388078391552, 0.028431806713342667, 0....",2.574138
2,261251,"[0.07000485807657242, -0.06418927758932114, -0...","[-0.010892418213188648, -0.038370147347450256,...","[0.068740316, -0.07668627, -0.0019331452, 0.05...",68.40,1,"[-0.007928319275379181, -0.07840053737163544, ...",0.678034
3,55858,"[-0.04193189740180969, -0.02518327534198761, 0...","[0.058143433183431625, -0.004104044754058123, ...","[-0.054631617, -0.019430207, 0.017474938, -0.1...",11.25,1,"[0.014764228835701942, 0.012520834803581238, 0...",3.412467
4,292686,"[0.021312430500984192, 0.0017853323370218277, ...","[-0.035538848489522934, 0.009405052289366722, ...","[0.015381876, -0.00023277814, -0.08660597, 0.0...",12.00,2,"[0.0014492346672341228, -0.0001916056789923459...",4.197052

In [342]:
final_data.head()

,sample_id,text_embeddings,image_embeddings,brand_product_embedding,total_value,unit_idx,extra_attributes_emb,price_log
0,33127,"[0.036331795156002045, -0.052913691848516464, ...","[0.009049994871020317, 0.00274485326372087, -0...","[-0.006221588, -0.046351764, -0.026960287, 0.0...",432.00,0,"[0.0014492346672341228, -0.0001916056789923459...",1.587192
1,198967,"[-0.01868608593940735, -0.013683686032891273, ...","[0.014290607534348965, -0.04910419136285782, 0...","[-0.018365428, -0.007958315, -0.034231354, 0.0...",128.00,1,"[-0.0375388078391552, 0.028431806713342667, 0....",2.574138
2,261251,"[0.07000485807657242, -0.06418927758932114, -0...","[-0.010892418213188648, -0.038370147347450256,...","[0.068740316, -0.07668627, -0.0019331452, 0.05...",68.40,1,"[-0.007928319275379181, -0.07840053737163544, ...",0.678034
3,55858,"[-0.04193189740180969, -0.02518327534198761, 0...","[0.058143433183431625, -0.004104044754058123, ...","[-0.054631617, -0.019430207, 0.017474938, -0.1...",11.25,1,"[0.014764228835701942, 0.012520834803581238, 0...",3.412467
4,292686,"[0.021312430500984192, 0.0017853323370218277, ...","[-0.035538848489522934, 0.009405052289366722, ...","[0.015381876, -0.00023277814, -0.08660597, 0.0...",12.00,2,"[0.0014492346672341228, -0.0001916056789923459...",4.197052

In [341]:

final_data.to_csv('train_final_dataset_pitstop7486_s3.csv')

In [347]:
# Example: drop columns you don’t need
cols_to_drop = [

    "extra_attributes_emb",
    "text_embeddings",
    "image_embeddings",
    "brand_product_embedding"

]

# Drop them directly from train and test
final_data.drop(columns=cols_to_drop, inplace=True, errors="ignore")


print("✅ Dropped unnecessary columns")
print("Remaining columns in train:", final_data.columns.tolist())

✅ Dropped unnecessary columns
Remaining columns in train: ['sample_id', 'total_value', 'unit_idx', 'price_log']

In [348]:
final_data.head()

   sample_id  total_value  unit_idx  price_log
0      33127       432.00         0   1.587192
1     198967       128.00         1   2.574138
2     261251        68.40         1   0.678034
3      55858        11.25         1   3.412467
4     292686        12.00         2   4.197052

In [288]:
final_data.shape[0]

75000

In [349]:

final_data.to_csv('train_final_dataset_pitstop7486_finale_s3.csv')